import React, {useState, useEffect, useRef, useCallback} from 'react';
import {createRoot} from 'react-dom/client';
import 'maplibre-gl/dist/maplibre-gl.css';
import {Map as Maplibre, useControl} from 'react-map-gl/maplibre';
import {MapboxOverlay as DeckOverlay} from '@deck.gl/mapbox';
import {PolygonLayer} from '@deck.gl/layers';
import {Color} from '@deck.gl/core';
import {cellToBoundary, cellToLonLat} from 'a5';
import type {MapRef} from 'react-map-gl/maplibre';

// Loaded at runtime from the CDN, which also serves the WASM binary and worker.
// 1.33.x runs DuckDB v1.5, required for the a5 extension's traversal functions
// (a5_spherical_cap, a5_grid_disk) — the v1.4.x extension builds predate them
const DUCKDB_BUNDLE = 'https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.33.1-dev57.0/+esm';

type DuckDBConnection = {
  query: (sql: string) => Promise<any>;
  close: () => Promise<void>;
};

// Hosted parquets exposed as tables under short names for queries:
// - population: aggregated from Kontur Population (CC BY 4.0) with prepare.sql
// - countries: compacted res-9 cell coverage of Natural Earth countries,
//   generated by examples/cli/country-polygons/countries.js
// - elevation/temperature: res-9 land cells sampled from ETOPO 2022 /
//   WorldClim 2.1, generated by prepare_climate.py
const DATASETS = {
  population: '/data/population.parquet',
  countries: '/data/countries.parquet',
  elevation: '/data/elevation.parquet',
  temperature: '/data/temperature.parquet'
};
const INITIAL_VIEW_STATE = {longitude: 10, latitude: 30, zoom: 1.7};

const DEFAULT_QUERY = `SELECT
  a5_cell_to_parent(cell, 6) AS cell,
  SUM(population) AS population
FROM population
GROUP BY 1`;

const PRESETS: {label: string; query: string}[] = [
  {label: 'World', query: DEFAULT_QUERY},
  {
    label: 'Brazil population',
    query: `-- Countries are stored as compacted cells, uncompact
-- to resolution 9 to match the population table
SELECT cell, population
FROM population
WHERE cell IN (
  SELECT unnest(a5_uncompact(list(cell), 9))
  FROM countries
  WHERE name = 'Brazil'
)`
  },
  {
    label: 'Chile elevation',
    query: `-- The same country boundary filters any dataset
-- indexed with A5 — here ETOPO 2022 elevation (m)
SELECT cell, elevation AS value
FROM elevation
WHERE cell IN (
  SELECT unnest(a5_uncompact(list(cell), 9))
  FROM countries
  WHERE name = 'Chile'
)`
  },
  {
    label: 'Japan temperature',
    query: `-- Annual mean temperature (°C), WorldClim 2.1
SELECT cell, temperature AS value
FROM temperature
WHERE cell IN (
  SELECT unnest(a5_uncompact(list(cell), 9))
  FROM countries
  WHERE name = 'Japan'
)`
  },
  {
    label: 'Denver terrain',
    query: `-- Terrain within 1000km of Denver: cover the circle
-- with a5_spherical_cap, then look up elevation by cell
SELECT cell, elevation AS value
FROM elevation
WHERE cell IN (
  SELECT unnest(a5_uncompact(
    a5_spherical_cap(a5_lonlat_to_cell(-104.99, 39.74, 9), 1000000.0), 9))
)`
  },
  {
    label: 'City buffers',
    query: `WITH cities(name, lon, lat) AS (
  VALUES ('London', -0.1276, 51.5074),
         ('New York', -74.006, 40.7128),
         ('Tokyo', 139.6917, 35.6895),
         ('São Paulo', -46.6333, -23.5505),
         ('Lagos', 3.3792, 6.5244),
         ('Delhi', 77.209, 28.6139)
)
-- All cells within 50km of a city
SELECT cell, population
FROM population
WHERE cell IN (
  SELECT unnest(a5_uncompact(
    a5_spherical_cap(a5_lonlat_to_cell(lon, lat, 9), 50000.0), 9))
  FROM cities
)`
  },
  {
    label: 'High altitude',
    query: `-- People living above 2500m: two datasets
-- joined directly on the cell ID
SELECT cell, population
FROM population
JOIN elevation USING (cell)
WHERE elevation > 2500`
  },
  {
    label: 'Lived climate',
    query: `-- Population-weighted temperature: the climate
-- people actually experience, aggregated to parent cells
SELECT
  a5_cell_to_parent(cell, 7) AS cell,
  ROUND(SUM(temperature * population) / SUM(population), 1) AS value
FROM temperature
JOIN population USING (cell)
GROUP BY 1
HAVING SUM(population) > 1000`
  }
];

// Above this, converting cells to boundaries and tessellating them can freeze
// the page for a long time, so ask before rendering (the query itself is fast)
const RENDER_WARNING_CELLS = 200_000;

type CellRow = {cell: bigint; value: number};
// `population` values are colored on a log scale, generic `value` columns linearly
type ValueField = 'population' | 'value' | null;
type QueryResult = {
  rows: CellRow[];
  minValue: number;
  maxValue: number;
  field: ValueField;
  elapsedMs: number;
  autoPalette: PaletteName;
};

const PALETTES = {
  // Dark blue -> magenta -> yellow, good on the dark basemap
  Magma: [
    [11, 4, 5],
    [59, 15, 112],
    [140, 41, 129],
    [222, 73, 104],
    [254, 159, 109],
    [252, 253, 191]
  ],
  Viridis: [
    [68, 1, 84],
    [65, 68, 135],
    [42, 120, 142],
    [34, 168, 132],
    [122, 209, 81],
    [253, 231, 37]
  ],
  // Hypsometric tints: green lowlands -> brown mountains -> white peaks
  Terrain: [
    [0, 68, 27],
    [35, 132, 67],
    [173, 209, 105],
    [222, 190, 113],
    [155, 106, 61],
    [245, 245, 245]
  ],
  // Diverging cold -> hot
  Heat: [
    [49, 54, 149],
    [116, 173, 209],
    [224, 243, 248],
    [254, 224, 144],
    [244, 109, 67],
    [165, 0, 38]
  ]
} satisfies Record<string, Color[]>;

type PaletteName = keyof typeof PALETTES;
type PaletteChoice = 'Auto' | PaletteName;

// Pick a palette to match the data: population densities read best on Magma,
// while elevation/temperature have conventional color schemes
function autoPalette(field: ValueField, sql: string): PaletteName {
  if (field === 'population') return 'Magma';
  const source = sql.toLowerCase();
  if (source.includes('temperature')) return 'Heat';
  if (source.includes('elevation')) return 'Terrain';
  return 'Viridis';
}

function valueToColor(value: number, {field, minValue, maxValue}: QueryResult, ramp: Color[]): Color {
  const t =
    field === 'population'
      ? Math.log10(1 + Math.max(value, 0)) / Math.log10(1 + maxValue)
      : (value - minValue) / (maxValue - minValue || 1);
  const s = Math.min(Math.max(t, 0), 1) * (ramp.length - 1);
  const i = Math.min(Math.floor(s), ramp.length - 2);
  const f = s - i;
  const [r0, g0, b0] = ramp[i];
  const [r1, g1, b1] = ramp[i + 1];
  return [r0 + (r1 - r0) * f, g0 + (g1 - g0) * f, b0 + (b1 - b0) * f, 255] as Color;
}

function formatValue(value: number): string {
  return Number.isInteger(value) ? value.toLocaleString() : value.toFixed(1);
}

// SUM() returns HUGEINT/DECIMAL, plain columns BIGINT or DOUBLE - coerce all to number
function toNumber(value: unknown): number {
  if (typeof value === 'number') return value;
  if (typeof value === 'bigint') return Number(value);
  return Number(String(value));
}

// Minimal SQL syntax highlighting (GitHub-light palette). A hand-rolled
// tokenizer keeps the example dependency-free.
const SQL_KEYWORDS = new Set(
  `select from where group order by having join using in as with values and or not
   limit union all on case when then else end distinct create table between like is null`.split(/\s+/)
);
const SQL_TOKEN = /--[^\n]*|'(?:[^']|'')*'|\b\d+(?:\.\d+)?\b|\b[A-Za-z_][A-Za-z0-9_]*\b/g;

function highlightSQL(sql: string): React.ReactNode[] {
  const out: React.ReactNode[] = [];
  let last = 0;
  let match: RegExpExecArray | null;
  SQL_TOKEN.lastIndex = 0;
  while ((match = SQL_TOKEN.exec(sql))) {
    if (match.index > last) out.push(sql.slice(last, match.index));
    const token = match[0];
    let color: string | undefined;
    let fontStyle: string | undefined;
    if (token.startsWith('--')) {
      color = '#6e7781';
      fontStyle = 'italic';
    } else if (token.startsWith("'")) {
      color = '#0a3069';
    } else if (/^\d/.test(token)) {
      color = '#0550ae';
    } else if (SQL_KEYWORDS.has(token.toLowerCase())) {
      color = '#cf222e';
    } else if (token.toLowerCase().startsWith('a5_')) {
      color = '#00875f';
    } else if (/^(sum|avg|min|max|count|round|unnest|list|len)$/i.test(token)) {
      color = '#8250df';
    }
    out.push(
      color ? (
        <span key={out.length} style={{color, fontStyle}}>
          {token}
        </span>
      ) : (
        token
      )
    );
    last = match.index + token.length;
  }
  if (last < sql.length) out.push(sql.slice(last));
  return out;
}

// Shared by the highlight layer and the textarea so they overlay exactly
const EDITOR_FONT: React.CSSProperties = {
  fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
  fontSize: '13px',
  lineHeight: '1.5',
  padding: '10px',
  margin: 0,
  border: 'none',
  whiteSpace: 'pre',
  boxSizing: 'border-box'
};

async function initDuckDB(): Promise<DuckDBConnection> {
  const duckdb = await import(/* webpackIgnore: true */ DUCKDB_BUNDLE);
  const bundle = await duckdb.selectBundle(duckdb.getJsDelivrBundles());
  const workerUrl = URL.createObjectURL(
    new Blob([`importScripts("${bundle.mainWorker}");`], {type: 'text/javascript'})
  );
  const worker = new Worker(workerUrl);
  const db = new duckdb.AsyncDuckDB(new duckdb.VoidLogger(), worker);
  await db.instantiate(bundle.mainModule, bundle.pthreadWorker);
  URL.revokeObjectURL(workerUrl);

  for (const [table, dataUrl] of Object.entries(DATASETS)) {
    const url = new URL(dataUrl, window.location.origin).href;
    await db.registerFileURL(`${table}.parquet`, url, duckdb.DuckDBDataProtocol.HTTP, false);
  }

  const connection = await db.connect();
  await connection.query(`INSTALL a5 FROM community; LOAD a5;`);
  // Materialize as tables so interactive queries run against memory
  for (const table of Object.keys(DATASETS)) {
    await connection.query(`CREATE TABLE ${table} AS SELECT * FROM '${table}.parquet'`);
  }
  return connection;
}

// Pan/zoom the map to roughly frame the query result. Cell centers are
// sampled (the fit doesn't need to be exact) and near-global results are
// left alone rather than zooming out to a degenerate world view
function fitMapToRows(map: MapRef | null, rows: CellRow[]) {
  if (!map || rows.length === 0) return;
  let minLon = Infinity;
  let maxLon = -Infinity;
  let minLat = Infinity;
  let maxLat = -Infinity;
  const stride = Math.max(1, Math.floor(rows.length / 2000));
  for (let i = 0; i < rows.length; i += stride) {
    const [lon, lat] = cellToLonLat(rows[i].cell);
    if (lon < minLon) minLon = lon;
    if (lon > maxLon) maxLon = lon;
    if (lat < minLat) minLat = lat;
    if (lat > maxLat) maxLat = lat;
  }
  if (maxLon - minLon > 300) return;
  // Keep the result clear of the query panel (left) and info card (right)
  const wide = map.getContainer().clientWidth > 1200;
  map.fitBounds(
    [
      [minLon, minLat],
      [maxLon, maxLat]
    ],
    {
      padding: {top: 40, bottom: 40, right: wide ? 360 : 40, left: wide ? 490 : 40},
      maxZoom: 9,
      duration: 1500
    }
  );
}

const App: React.FC = () => {
  const connectionRef = useRef<DuckDBConnection | null>(null);
  const mapRef = useRef<MapRef | null>(null);
  const [status, setStatus] = useState<string>('Starting DuckDB…');
  const [error, setError] = useState<string | null>(null);
  const [query, setQuery] = useState<string>(DEFAULT_QUERY);
  const [running, setRunning] = useState<boolean>(false);
  const [result, setResult] = useState<QueryResult | null>(null);
  const [palette, setPalette] = useState<PaletteChoice>('Auto');
  // Query result held back from rendering until the user confirms
  const [pending, setPending] = useState<{table: any; elapsedMs: number; sql: string} | null>(null);
  const highlightRef = useRef<HTMLPreElement | null>(null);

  const displayTable = useCallback((table: any, elapsedMs: number, sql: string) => {
    const field: ValueField = table.schema.fields.some(f => f.name === 'population')
      ? 'population'
      : table.schema.fields.some(f => f.name === 'value')
        ? 'value'
        : null;

    const rows: CellRow[] = [];
    let minValue = Infinity;
    let maxValue = -Infinity;
    for (const row of table) {
      const value = field ? toNumber(row[field]) : 1;
      if (value < minValue) minValue = value;
      if (value > maxValue) maxValue = value;
      rows.push({cell: BigInt(row.cell), value});
    }
    setResult({rows, minValue, maxValue, field, elapsedMs, autoPalette: autoPalette(field, sql)});
    setStatus(`${rows.length.toLocaleString()} cells · ${Math.round(elapsedMs)}ms`);
    fitMapToRows(mapRef.current, rows);
  }, []);

  const runQuery = useCallback(
    async (sql: string) => {
      const connection = connectionRef.current;
      if (!connection) return;
      setRunning(true);
      setError(null);
      setPending(null);
      try {
        const start = performance.now();
        const table = await connection.query(sql);
        const elapsedMs = performance.now() - start;

        if (!table.schema.fields.some(f => f.name === 'cell')) {
          throw new Error(`Query must return a 'cell' column`);
        }
        if (table.numRows > RENDER_WARNING_CELLS) {
          setPending({table, elapsedMs, sql});
          setStatus(
            `Query returned ${table.numRows.toLocaleString()} cells in ${Math.round(elapsedMs)}ms — ` +
              `rendering this many may freeze the page for a while`
          );
          return;
        }
        displayTable(table, elapsedMs, sql);
      } catch (e) {
        setError((e as Error).message);
      } finally {
        setRunning(false);
      }
    },
    [displayTable]
  );

  useEffect(() => {
    let cancelled = false;
    initDuckDB()
      .then(connection => {
        if (cancelled) {
          connection.close();
          return;
        }
        connectionRef.current = connection;
        setStatus('Running query…');
        runQuery(DEFAULT_QUERY);
      })
      .catch(e => setError((e as Error).message));
    return () => {
      cancelled = true;
      connectionRef.current?.close();
      connectionRef.current = null;
    };
  }, [runQuery]);

  const paletteName: PaletteName = palette === 'Auto' ? (result?.autoPalette ?? 'Magma') : palette;
  const ramp = PALETTES[paletteName];

  const cellLayer = new PolygonLayer<CellRow>({
    id: 'query-cells',
    data: result?.rows ?? [],
    getPolygon: d => cellToBoundary(d.cell),
    getFillColor: d => (result ? valueToColor(d.value, result, ramp) : [0, 0, 0, 0]),
    stroked: false,
    pickable: true,
    beforeId: 'watername_ocean',
    parameters: {cullMode: 'back', depthCompare: 'always'} as const,
    updateTriggers: {getFillColor: [result?.field, result?.minValue, result?.maxValue, paletteName]}
  });

  const onKeyDown = (e: React.KeyboardEvent) => {
    if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') {
      e.preventDefault();
      runQuery(query);
    }
  };

  return (
    <div
      style={{
        position: 'absolute',
        height: '100%',
        width: '100%',
        top: 0,
        left: 0,
        background: 'linear-gradient(0, #000, #223)'
      }}
    >
      <Maplibre
        id="map"
        ref={mapRef}
        initialViewState={INITIAL_VIEW_STATE}
        projection="globe"
        mapStyle="https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json"
        dragRotate={false}
        maxPitch={0}
      >
        <DeckGLOverlay
          layers={[cellLayer]}
          interleaved={true}
          getTooltip={({object}) =>
            object && {
              html: `<div>${result?.field === 'population' ? 'Population' : 'Value'}: ${
                Number.isInteger(object.value) ? object.value.toLocaleString() : object.value.toFixed(1)
              }</div>`,
              style: {
                backgroundColor: 'white',
                padding: '8px',
                borderRadius: '4px',
                boxShadow: '0 2px 4px rgba(0,0,0,0.2)'
              }
            }
          }
        />
      </Maplibre>
      <div
        style={{
          position: 'absolute',
          top: '20px',
          left: '20px',
          zIndex: 1,
          width: '440px',
          maxWidth: 'calc(100% - 40px)',
          background: 'rgba(255, 255, 255, 0.96)',
          borderRadius: '8px',
          padding: '12px',
          boxShadow: '0 2px 8px rgba(0,0,0,0.25)',
          color: '#222',
          fontFamily: 'sans-serif',
          fontSize: '13px'
        }}
      >
        <div
          style={{
            position: 'relative',
            height: '230px',
            resize: 'vertical',
            overflow: 'hidden',
            minHeight: '100px',
            background: '#f6f8fa',
            border: '1px solid #d0d7de',
            borderRadius: '4px'
          }}
        >
          <pre
            ref={highlightRef}
            aria-hidden
            style={{...EDITOR_FONT, position: 'absolute', inset: 0, overflow: 'hidden', color: '#1f2328'}}
          >
            {highlightSQL(query)}
            {'\n'}
          </pre>
          <textarea
            value={query}
            onChange={e => setQuery(e.target.value)}
            onKeyDown={onKeyDown}
            onScroll={e => {
              const pre = highlightRef.current;
              if (pre) {
                pre.scrollTop = e.currentTarget.scrollTop;
                pre.scrollLeft = e.currentTarget.scrollLeft;
              }
            }}
            spellCheck={false}
            wrap="off"
            style={{
              ...EDITOR_FONT,
              position: 'absolute',
              inset: 0,
              width: '100%',
              height: '100%',
              background: 'transparent',
              color: 'transparent',
              caretColor: '#1f2328',
              resize: 'none',
              outline: 'none'
            }}
          />
        </div>
        <div style={{display: 'flex', alignItems: 'baseline', gap: '6px', flexWrap: 'wrap', marginTop: '8px', color: '#666'}}>
          Tables:
          {Object.keys(DATASETS).map(table => (
            <code
              key={table}
              style={{
                background: '#f6f8fa',
                border: '1px solid #d0d7de',
                borderRadius: '4px',
                padding: '1px 5px',
                color: '#1f2328'
              }}
            >
              {table}
            </code>
          ))}
        </div>
        <div style={{display: 'flex', gap: '6px', marginTop: '8px'}}>
          <button
            onClick={() => runQuery(query)}
            disabled={running || !connectionRef.current}
            style={{
              background: '#00aa55',
              color: 'white',
              border: 'none',
              borderRadius: '4px',
              padding: '6px 14px',
              cursor: 'pointer',
              fontWeight: 'bold'
            }}
          >
            {running ? 'Running…' : 'Run ⌘⏎'}
          </button>
          <select
            value={palette}
            onChange={e => setPalette(e.target.value as PaletteChoice)}
            title="Color palette"
            style={{
              marginLeft: 'auto',
              background: 'white',
              color: '#333',
              border: '1px solid #d0d7de',
              borderRadius: '4px',
              padding: '6px 4px',
              cursor: 'pointer'
            }}
          >
            <option value="Auto">Palette: Auto</option>
            {Object.keys(PALETTES).map(name => (
              <option key={name} value={name}>
                {name}
              </option>
            ))}
          </select>
        </div>
        <div style={{display: 'flex', gap: '6px', flexWrap: 'wrap', marginTop: '8px'}}>
          {PRESETS.map(preset => (
            <button
              key={preset.label}
              onClick={() => {
                setQuery(preset.query);
                runQuery(preset.query);
              }}
              disabled={running || !connectionRef.current}
              style={{
                background: 'white',
                color: '#333',
                border: '1px solid #d0d7de',
                borderRadius: '4px',
                padding: '6px 8px',
                cursor: 'pointer'
              }}
            >
              {preset.label}
            </button>
          ))}
        </div>
        <div style={{marginTop: '8px', minHeight: '16px', color: error ? '#c00' : pending ? '#9a6700' : '#666'}}>
          {error ?? status}
        </div>
        {result && result.field && (
          <div style={{display: 'flex', alignItems: 'center', gap: '8px', marginTop: '6px', color: '#666'}}>
            <span>{formatValue(result.minValue)}</span>
            <div
              style={{
                flex: 1,
                height: '8px',
                borderRadius: '4px',
                background: `linear-gradient(90deg, ${ramp.map(([r, g, b]) => `rgb(${r},${g},${b})`).join(', ')})`
              }}
            />
            <span>{formatValue(result.maxValue)}</span>
          </div>
        )}
        {pending && (
          <div style={{display: 'flex', gap: '6px', marginTop: '8px'}}>
            <button
              onClick={() => {
                displayTable(pending.table, pending.elapsedMs, pending.sql);
                setPending(null);
              }}
              style={{
                background: '#bf8700',
                color: 'white',
                border: 'none',
                borderRadius: '4px',
                padding: '6px 14px',
                cursor: 'pointer',
                fontWeight: 'bold'
              }}
            >
              Render anyway
            </button>
            <button
              onClick={() => {
                setPending(null);
                setStatus(`Rendering cancelled — add an aggregation (e.g. a5_cell_to_parent) to reduce the cell count`);
              }}
              style={{
                background: 'white',
                color: '#333',
                border: '1px solid #d0d7de',
                borderRadius: '4px',
                padding: '6px 14px',
                cursor: 'pointer'
              }}
            >
              Cancel
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

export default App;

export async function renderToDOM(container: HTMLDivElement) {
  const root = createRoot(container);
  root.render(<App />);
}

function DeckGLOverlay(props) {
  const overlay = useControl(() => new DeckOverlay(props));
  overlay.setProps(props);
  return null;
}
