import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {
  AdditiveBlending,
  BackSide,
  BufferAttribute,
  BufferGeometry,
  Color,
  DataTexture,
  DoubleSide,
  FloatType,
  HalfFloatType,
  LinearSRGBColorSpace,
  Group,
  Matrix3,
  Matrix4,
  Mesh,
  MeshBasicMaterial,
  PerspectiveCamera,
  PlaneGeometry,
  RedFormat,
  Scene,
  ShaderMaterial,
  Sphere,
  SphereGeometry,
  Vector2,
  Vector3,
  WebGLRenderTarget,
  WebGLRenderer
} from 'three';
import {EffectComposer} from 'three/examples/jsm/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/examples/jsm/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/examples/jsm/postprocessing/UnrealBloomPass.js';

import {computeGlobe} from './globe';
import {getPentagonCenter, getPentagonVertices} from 'a5/core/tiling';
import {FaceToIJ} from 'a5/core/coordinate-transforms';
import {roundToTriple, tripleToS} from 'a5/lattice';
import {migrate} from 'a5/core/migrate';
// Small parquet reader: reads just the columns asked for, with range requests
import {asyncBufferFromUrl, parquetMetadata, parquetRead} from 'hyparquet';

// Resolution 7 cells with the chunk each moves with and a column per dataset,
// generated by prepare.sql from the DuckDB playground's datasets
const DATA_URL = '/data/homepage.parquet';

// Magma, minus its near-black first stop so sparse cells stay visible
const MAGMA = [
  [59, 15, 112],
  [140, 41, 129],
  [222, 73, 104],
  [254, 159, 109],
  [252, 253, 191]
];
// Hypsometric tints: green lowlands -> brown mountains -> white peaks
const TERRAIN = [
  [0, 68, 27],
  [35, 132, 67],
  [173, 209, 105],
  [222, 190, 113],
  [155, 106, 61],
  [245, 245, 245]
];
// Diverging cold -> hot
const HEAT = [
  [49, 54, 149],
  [116, 173, 209],
  [224, 243, 248],
  [254, 224, 144],
  [244, 109, 67],
  [165, 0, 38]
];

// Cartographic palette from the country-polygons example, indexed by
// Natural Earth's mapcolor7 (a coloring where neighboring countries differ)
const COUNTRY_PALETTE = [
  [45, 80, 4],
  [145, 183, 217],
  [118, 176, 66],
  [4, 45, 80],
  [220, 227, 222],
  [82, 128, 35],
  [8, 89, 159]
];

// Cells with no country (remote islands) in the countries view
const UNCATEGORIZED = [90, 90, 100];

type Dataset = {
  // Column of the data file holding the value to color by, every cell has
  // one (see prepare.sql). Without one, the value comes from the chunk id
  column?: string;
  fromChunk?: (chunk: number) => number;
  // Shown under the globe
  label: string;
  ramp: number[][];
  // Where values fall on the ramp between their min and max, or 'categorical'
  // for values that index the ramp from 1
  scale: 'log' | 'sqrt' | 'linear' | 'categorical';
};

// Cycled through in order, same sources and palettes as the DuckDB playground.
// Elevation first, as its greens suit the site
const DATASETS: Dataset[] = [
  // Most land is low lying, sqrt spreads the lowlands over more of the ramp
  {column: 'elevation', label: 'Elevation', ramp: TERRAIN, scale: 'sqrt'},
  {column: 'population', label: 'Population', ramp: MAGMA, scale: 'log'},
  {column: 'temperature', label: 'Temperature', ramp: HEAT, scale: 'linear'},
  // Chunk ids pack in each country's mapcolor7 (see prepare.sql), 0 for none
  {fromChunk: chunk => (chunk >> 4) & 7, label: 'Countries', ramp: COUNTRY_PALETTE, scale: 'categorical'}
];

// Dataset cycle: once a dataset has been on the globe for GLOBE_SECONDS, and
// the user hasn't dragged for IDLE_SECONDS, gather all its cells into the
// logo, hold, then drop the logo out of view and spring the next dataset's
// logo in from above before releasing it onto the globe. The arrow buttons
// run the same transition on demand, in either direction
const GLOBE_SECONDS = 60;
const IDLE_SECONDS = 10;
const HOLD_SECONDS = 0.6;
const DROP_OUT_SECONDS = 0.6;
// Empty pause between the old logo leaving and the new one arriving
const GAP_SECONDS = 0.5;
const DROP_IN_SECONDS = 1.2;

const LOGO_TEXT = 'A5';
// The mosaic tiles are A5's pentagons: a patch of the planar A5 lattice (as on
// a dodecahedron face, before projection to the sphere) at this resolution,
// clipped to the rendered text
const LOGO_RESOLUTION = 8;
// Roughly how many tiles make up the logo
const LOGO_TILES = 5000;

// A chunk returns to the globe as soon as its center faces the camera
const RETURN_FACING = 0.05;

// Animation parameters
const PARAMETERS = {
  // Duration of one chunk's flight
  flightSeconds: 1.6,
  // How far apart in time cells within a chunk set off (0: all together)
  stagger: 0.6,
  // How far round the back of the globe a chunk's center must be before it
  // leaves, in degrees past the limb, deep enough to leave out of sight
  leaveAngle: 30,
  // Chunks only leave after being hidden this long, so turning the globe
  // first shows cells arriving, then the far side peeling off
  leaveDelay: 1,
  // Departing cells' initial velocity straight out from the surface
  launch: 1,
  // Departing cells swing round a waypoint this far behind the globe...
  behind: 0.6,
  // ...and this far out from its center, on the logo side (globe radii)
  wide: 1.3,
  // Random scatter of each cell's path
  spread: 0.9,
  // How far cells lift off the logo towards the camera as they leave it, as a
  // fraction of the logo's distance. Arrivals come in from behind
  logoLift: 0.2,
  // The logo's tiles each hold a stack of cells, one per pass of the cells
  // over the tiles: the gap between these layers, in logo widths
  layerSpacing: 0.07,
  // The logo is a mass on a damped spring along the line of sight. Departing
  // cells push it back and arriving ones forwards, with an impulse of push
  // times the share of the dataset's cells moving
  logoPush: 2.5,
  logoMass: 1,
  springStiffness: 40,
  springDamping: 4,
  // The spring stiffens past this displacement (a fraction of the logo's
  // distance), so small kicks register but big ones are reined in. 0 is linear
  springRange: 0.04,
  // Glow around the brightest cells and stars
  bloom: 0.35,
  // How far the glow spreads
  bloomRadius: 0.5,
  // Brightness above which pixels glow: lower spreads it to more of the scene
  bloomThreshold: 0.35,
  // Motion blur: how long the shutter is open, stretching cells in flight
  shutter: 0.01,
  // Scales the stars' cores: smaller is sharper
  starSize: 1,
  starIntensity: 1
};

// Per-chunk flight progress lives in a float texture this wide
const PROGRESS_TEXTURE_WIDTH = 256;

const INITIAL_LONGITUDE = 10;
const INITIAL_LATITUDE = 20;
const AUTO_ROTATE_SPEED = 4; // degrees per second
const AUTO_ROTATE_DELAY = 2000; // ms of inactivity before auto-rotation resumes
const INITIAL_ROTATE_DELAY = 10000; // ms after the first interaction before auto-rotation resumes

type LogoTiles = {
  // 5 vertices (x, y) per tile, in logo units: width 1, centered on the origin
  vertices: Float32Array;
  // Tile centers (x, y), the point cells fly to. Tiles are ordered along the
  // A5 space-filling curve, so consecutive tiles are neighbors
  centers: Float32Array;
  count: number;
  height: number;
};

type DataFile = {
  // Reads whole columns, in row order
  readColumns: (columns: string[]) => Promise<Record<string, any[]>>;
};

async function openDataFile(): Promise<DataFile> {
  const url = new URL(DATA_URL, window.location.origin).href;
  // One request for the end of the file gets both the footer (a few KB) and,
  // from Content-Range, the file's size, which hyparquet would otherwise
  // fetch with a HEAD request first. A server ignoring the range sends the
  // whole file, which serves just as well
  const response = await fetch(url, {headers: {Range: 'bytes=-16384'}});
  const tail = await response.arrayBuffer();
  const byteLength = Number(response.headers.get('Content-Range')?.split('/')[1]) || tail.byteLength;
  const metadata = parquetMetadata(tail);
  // Then fetch columns on demand
  const file =
    response.status === 206
      ? await asyncBufferFromUrl({url, byteLength})
      : {byteLength, slice: (start: number, end?: number) => tail.slice(start, end)};
  const rowCount = Number(metadata.num_rows);
  return {
    readColumns: async columns => {
      const result: Record<string, any[]> = {};
      for (const column of columns) result[column] = new Array(rowCount);
      await parquetRead({
        file,
        metadata,
        columns,
        // Column data arrives in chunks (one per row group)
        onChunk: ({columnName, columnData, rowStart}) => {
          const out = result[columnName];
          for (let i = 0; i < columnData.length; i++) out[rowStart + i] = columnData[i];
        }
      });
      return result;
    }
  };
}

// A5's planar lattice: a periodic tiling by one pentagon in four orientations
// (flavors). Lattice points are triples (x, y, z) with x + y + z = 0 or 1, and
// a point's flavor follows from that parity and the parity of y, as the A5
// curve's descent (sToCell) produces it. Positions are in the unit-scale
// lattice, which is a quintant at resolution LOGO_RESOLUTION scaled up by
// 2^LOGO_RESOLUTION
type LatticePoint = {x: number; y: number; z: number};
function latticeFlavor({x, y, z}: LatticePoint): number {
  const parity = x + y + z;
  return parity | ((parity ^ (y & 1)) << 1);
}

// The four flavors' pentagons, as vertex offsets from the pentagon's center
const FLAVOR_SHAPES = [0, 1, 2, 3].map(flavor => {
  // A lattice point of each flavor, see latticeFlavor
  const point = [
    {x: 0, y: 0, z: 0},
    {x: 0, y: 1, z: 0},
    {x: 0, y: 1, z: -1},
    {x: 0, y: 0, z: 1}
  ][flavor];
  const center = getPentagonCenter(0, 0, point, flavor);
  return getPentagonVertices(0, 0, point, flavor)
    .getVertices()
    .map(([vx, vy]) => [vx - center[0], vy - center[1]]);
});

// Render the text to a canvas, then keep the lattice pentagons whose centers
// land on it
function createLogoTiles(): LogoTiles {
  const fontSize = 200;
  const font = `900 ${fontSize}px "Helvetica Neue", Helvetica, Arial, sans-serif`;
  const canvas = document.createElement('canvas');
  const ctx = canvas.getContext('2d', {willReadFrequently: true})!;
  ctx.font = font;
  const metrics = ctx.measureText(LOGO_TEXT);
  const pad = 4;
  const width = Math.ceil(metrics.actualBoundingBoxLeft + metrics.actualBoundingBoxRight) + 2 * pad;
  const height = Math.ceil(metrics.actualBoundingBoxAscent + metrics.actualBoundingBoxDescent) + 2 * pad;
  canvas.width = width;
  canvas.height = height;
  ctx.font = font;
  ctx.fillStyle = '#fff';
  ctx.fillText(LOGO_TEXT, pad + metrics.actualBoundingBoxLeft, pad + metrics.actualBoundingBoxAscent);
  const pixels = ctx.getImageData(0, 0, width, height).data;

  let filled = 0;
  for (let i = 3; i < pixels.length; i += 4) {
    if (pixels[i] > 127) filled++;
  }

  // Size the patch of lattice so that the text covers ~LOGO_TILES pentagons
  const fill = filled / (width * height);
  // getArea is the shoelace sum without the halving (its sign gives the winding)
  const tileArea = Math.abs(getPentagonVertices(0, 0, {x: 0, y: 0, z: 0}, 0).getArea()) / 2;
  const spanX = Math.sqrt(((LOGO_TILES / fill) * tileArea * width) / height);
  const spanY = (spanX * height) / width;

  // Center the patch on quintant 0 (a triangle with its apex at the face
  // center), so every tile is a cell of that quintant with a place on the A5
  // curve. Corners: the apex and the two ends of the last row
  const lastRow = 2 ** LOGO_RESOLUTION - 1;
  const corners = [
    {x: 0, y: 0, z: 0},
    {x: -lastRow, y: lastRow, z: 0},
    {x: 0, y: lastRow, z: -lastRow}
  ].map(point => getPentagonCenter(0, 0, point, latticeFlavor(point)));
  const centerX = (corners[0][0] + corners[1][0] + corners[2][0]) / 3;
  const centerY = (corners[0][1] + corners[1][1] + corners[2][1]) / 3;

  // Pentagon centers move linearly with x and y (flavors aside, which only
  // shift them within a tile), so invert that to find the range of lattice
  // points covering the patch
  const origin = getPentagonCenter(0, 0, {x: 0, y: 0, z: 0}, 0);
  const stepX = getPentagonCenter(0, 0, {x: 1, y: 0, z: -1}, 0);
  const stepY = getPentagonCenter(0, 0, {x: 0, y: 2, z: -2}, 0);
  const [ax, ay] = [stepX[0] - origin[0], stepX[1] - origin[1]];
  const [bx, by] = [(stepY[0] - origin[0]) / 2, (stepY[1] - origin[1]) / 2];
  const determinant = ax * by - ay * bx;
  let minX = Infinity;
  let maxX = -Infinity;
  let minY = Infinity;
  let maxY = -Infinity;
  for (const [cx, cy] of [
    [centerX - spanX / 2, centerY - spanY / 2],
    [centerX + spanX / 2, centerY - spanY / 2],
    [centerX + spanX / 2, centerY + spanY / 2],
    [centerX - spanX / 2, centerY + spanY / 2]
  ]) {
    const x = (by * (cx - origin[0]) - bx * (cy - origin[1])) / determinant;
    const y = (ax * (cy - origin[1]) - ay * (cx - origin[0])) / determinant;
    minX = Math.min(minX, x);
    maxX = Math.max(maxX, x);
    minY = Math.min(minY, y);
    maxY = Math.max(maxY, y);
  }

  const kept: {x: number; y: number; flavor: number; order: number}[] = [];
  for (let y = Math.floor(minY) - 2; y <= Math.ceil(maxY) + 2; y++) {
    for (let x = Math.floor(minX) - 2; x <= Math.ceil(maxX) + 2; x++) {
      for (let parity = 0; parity < 2; parity++) {
        const point = {x, y, z: parity - x - y};
        const flavor = latticeFlavor(point);
        const center = getPentagonCenter(0, 0, point, flavor);
        // In logo units: width 1, centered on the origin
        const u = (center[0] - centerX) / spanX;
        const v = (center[1] - centerY) / spanX;
        const col = Math.floor((u + 0.5) * width);
        const row = Math.floor((0.5 - (v * width) / height) * height);
        if (col < 0 || row < 0 || col >= width || row >= height) continue;
        if (pixels[(row * width + col) * 4 + 3] <= 127) continue;
        // Position on the A5 curve, from the cell's center (see lonLatToCell)
        const triple = roundToTriple(FaceToIJ(center as any), LOGO_RESOLUTION);
        const order = Number(tripleToS(triple, LOGO_RESOLUTION));
        kept.push({x: u, y: v, flavor, order});
      }
    }
  }
  // Along the A5 curve, so consecutive tiles are neighbors and each chunk of
  // cells fills a patch shaped by the curve (see createCellGeometry)
  kept.sort((a, b) => a.order - b.order);

  const vertices = new Float32Array(kept.length * 10);
  const centers = new Float32Array(kept.length * 2);
  for (let i = 0; i < kept.length; i++) {
    const {x, y, flavor} = kept[i];
    const shape = FLAVOR_SHAPES[flavor];
    for (let k = 0; k < 5; k++) {
      // Shrunk towards the center so the grout between tiles shows
      vertices[i * 10 + k * 2] = x + (shape[k][0] / spanX) * 0.85;
      vertices[i * 10 + k * 2 + 1] = y + (shape[k][1] / spanX) * 0.85;
    }
    centers[i * 2] = x;
    centers[i * 2 + 1] = y;
  }

  return {vertices, centers, count: kept.length, height: height / width};
}

function valueToColor(
  value: number,
  minValue: number,
  maxValue: number,
  {ramp, scale}: Dataset,
  out: Float32Array,
  offset: number
) {
  if (scale === 'categorical') {
    // Categories index the ramp from 1, 0 for none
    const color = ramp[value - 1] ?? UNCATEGORIZED;
    for (let c = 0; c < 3; c++) out[offset + c] = color[c] / 255;
    return;
  }
  const transform =
    scale === 'log'
      ? (x: number) => Math.log10(1 + Math.max(x, 0))
      : scale === 'sqrt'
        ? (x: number) => Math.sqrt(Math.max(x, 0))
        : (x: number) => x;
  const lo = transform(minValue);
  const t = (transform(value) - lo) / (transform(maxValue) - lo || 1);
  const s = Math.min(Math.max(t, 0), 1) * (ramp.length - 1);
  const i = Math.min(Math.floor(s), ramp.length - 2);
  const f = s - i;
  for (let c = 0; c < 3; c++) {
    out[offset + c] = (ramp[i][c] + (ramp[i + 1][c] - ramp[i][c]) * f) / 255;
  }
}

// Every cell carries both its position on the globe and its tile in the logo,
// the vertex shader places it between the two using its chunk's progress. All
// datasets share this geometry, each supplies only its colors (createFill).
//
// Rows arrive in logo order (see prepare.sql), laid along the tiles, wrapping
// round to the first tile each time they run out, so row r takes tile
// r % tiles in layer floor(r / tiles). The globe positions come later
// (setGlobe), until then the cells can only sit in the logo
function createCellGeometry(chunks: ArrayLike<number>, logo: LogoTiles) {
  const n = chunks.length;
  const tile = new Float32Array(n * 15);
  const tileCenter = new Float32Array(n * 15);
  const seed = new Float32Array(n * 5);
  const chunk = new Float32Array(n * 5);
  const index = new Uint32Array(n * 9);

  let chunkCount = 0;
  for (let i = 0; i < n; i++) if (chunks[i] + 1 > chunkCount) chunkCount = chunks[i] + 1;
  const chunkSizes = new Uint32Array(chunkCount);

  for (let i = 0; i < n; i++) {
    const t = i % logo.count;
    // Each pass is a layer at its own depth, see layerSpacing
    const layer = Math.floor(i / logo.count);
    const cellSeed = Math.random();
    for (let k = 0; k < 5; k++) {
      const v = i * 5 + k;
      tile[v * 3] = logo.vertices[t * 10 + k * 2];
      tile[v * 3 + 1] = logo.vertices[t * 10 + k * 2 + 1];
      tileCenter[v * 3] = logo.centers[t * 2];
      tileCenter[v * 3 + 1] = logo.centers[t * 2 + 1];
      tileCenter[v * 3 + 2] = layer;
      seed[v] = cellSeed;
      chunk[v] = chunks[i];
    }
    chunkSizes[chunks[i]]++;
    index.set([i * 5, i * 5 + 1, i * 5 + 2, i * 5, i * 5 + 2, i * 5 + 3, i * 5, i * 5 + 3, i * 5 + 4], i * 9);
  }

  const geometry = new BufferGeometry();
  geometry.setAttribute('tile', new BufferAttribute(tile, 3));
  geometry.setAttribute('tileCenter', new BufferAttribute(tileCenter, 3));
  geometry.setAttribute('seed', new BufferAttribute(seed, 1));
  geometry.setAttribute('chunk', new BufferAttribute(chunk, 1));
  geometry.setIndex(new BufferAttribute(index, 1));
  // Nothing reads these back once they're on the GPU, free the JS copies.
  // three would compute a bounding sphere from them (after uploading) to sort
  // the mesh, so give it one. Its value doesn't matter, the mesh isn't culled
  geometry.boundingSphere = new Sphere(new Vector3(), 1);
  for (const attribute of [...Object.values(geometry.attributes), geometry.index!]) {
    (attribute as BufferAttribute).onUpload(freeArray);
  }
  // Placeholders for the globe positions, filled in by setGlobe
  geometry.setAttribute('position', new BufferAttribute(new Float32Array(n * 15), 3));
  geometry.setAttribute('center', new BufferAttribute(new Float32Array(n * 15), 3));
  return {geometry, chunkSizes, chunkCount, seed};
}

// Fill in the geometry's globe positions from computeGlobe's arrays, and
// return each chunk's center: the normalized sum of its cells' centers
function setGlobe(
  geometry: BufferGeometry,
  chunks: ArrayLike<number>,
  chunkCount: number,
  {position, center}: ReturnType<typeof computeGlobe>
) {
  const chunkCenters = new Float32Array(chunkCount * 3);
  for (let i = 0; i < chunks.length; i++) {
    for (let c = 0; c < 3; c++) chunkCenters[chunks[i] * 3 + c] += center[i * 15 + c];
  }
  for (let c = 0; c < chunkCount; c++) {
    const [x, y, z] = chunkCenters.subarray(c * 3, c * 3 + 3);
    const length = Math.hypot(x, y, z) || 1;
    chunkCenters.set([x / length, y / length, z / length], c * 3);
  }
  for (const [name, array] of [
    ['position', position],
    ['center', center]
  ] as const) {
    const attribute = geometry.getAttribute(name) as BufferAttribute;
    attribute.array = array;
    attribute.needsUpdate = true;
    attribute.onUpload(freeArray);
  }
  return chunkCenters;
}

// computeGlobe in a worker, so the main thread stays free to animate the logo
// in meanwhile. Falls back to computing it here without worker support
function computeGlobeAsync(cells: BigUint64Array): Promise<ReturnType<typeof computeGlobe>> {
  let worker: Worker;
  try {
    worker = new Worker(new URL('./globe-worker.ts', import.meta.url));
  } catch {
    return Promise.resolve(computeGlobe(cells));
  }
  return new Promise(resolve => {
    worker.onmessage = event => {
      worker.terminate();
      resolve(event.data);
    };
    worker.onerror = () => {
      worker.terminate();
      resolve(computeGlobe(cells));
    };
    worker.postMessage({cells});
  });
}

function freeArray(this: {array: unknown}) {
  this.array = null;
}

// A dataset's cell colors, per vertex, for the shared geometry's fill
// attribute. seed is the geometry's per-vertex random value
function createFill(values: ArrayLike<number>, dataset: Dataset, seed: Float32Array) {
  const n = values.length;
  let minValue = Infinity;
  let maxValue = -Infinity;
  for (let i = 0; i < n; i++) {
    if (values[i] < minValue) minValue = values[i];
    if (values[i] > maxValue) maxValue = values[i];
  }
  const fill = new Float32Array(n * 15);
  const color = new Float32Array(3);
  for (let i = 0; i < n; i++) {
    valueToColor(values[i], minValue, maxValue, dataset, color, 0);
    // Flat country colors get a slight per-cell lightening so the tiles show
    if (dataset.scale === 'categorical') for (let c = 0; c < 3; c++) color[c] *= 1 + seed[i * 5] * 0.22;
    for (let k = 0; k < 5; k++) fill.set(color, (i * 5 + k) * 3);
  }
  const attribute = new BufferAttribute(fill, 3);
  attribute.onUpload(freeArray);
  return attribute;
}

// Pulls back slightly before accelerating away
function easeInBack(t: number, overshoot = 1.2): number {
  return (overshoot + 1) * t * t * t - overshoot * t * t;
}

// Damped spring from 0 to 1, overshooting by ~8% before settling
function springIn(t: number): number {
  return t >= 1 ? 1 : 1 - Math.exp(-7 * t) * Math.cos(9 * t);
}

const CELL_VERTEX_SHADER = /* glsl */ `
attribute vec3 center;
attribute vec3 tile;
// Tile center in logo units, and the cell's layer in the tile's stack
attribute vec3 tileCenter;
attribute vec3 fill;
attribute float seed;
attribute float chunk;
uniform sampler2D progress;
uniform mat3 rotation;
uniform vec3 globeCenter;
uniform float globeRadius;
uniform vec3 logoCenter;
uniform float logoScale;
// Shifts cells in the logo, for dropping it in and out of view
uniform vec3 logoOffset;
uniform float stagger;
uniform float launch;
uniform float behind;
uniform float wide;
uniform float spread;
uniform float logoLift;
// Gap between the logo's layers of cells, in logo widths
uniform float layerSpacing;
// Logo displacement towards the camera, as a fraction of its distance
uniform float logoDepth;
uniform float flightSeconds;
// Motion blur exposure, in seconds
uniform float shutter;
varying vec3 vColor;

const float PI = 3.14159265;

// This cell's flight time for a chunk progress p, with cells in a chunk
// setting off at different times but all arriving by p = 1
float flightTime(float p) {
  float t = clamp(p * (1.0 + stagger) - seed * stagger, 0.0, 1.0);
  return t * t * (3.0 - 2.0 * t);
}

// Where the cell's center is at flight time t: 0 on the globe, 1 in the logo
vec3 flightPath(float t, vec3 normal, vec3 start, vec3 end, vec3 toCamera, vec3 jitter, float lift) {
  float facing = dot(normal, toCamera);

  // Cells landing on the near side: straight in, bulging outwards, towards
  // the viewer and in a random direction per cell so the chunk scatters
  float side = clamp(facing * 4.0, -1.0, 1.0);
  vec3 bulge = (normal * 0.5 + toCamera * side * 1.5 + jitter * vec3(1.5, 1.5, 0.5) * spread) * globeRadius * 0.5;
  vec3 direct = mix(start, end, t) + bulge * sin(PI * t);

  // Cells leaving the far side: a cubic Bezier that launches straight out
  // from the surface, swings round a waypoint behind the globe just outside
  // its silhouette on the logo side, then comes forward to the tile. The
  // logo is nearer the camera than the globe, so a direct path would cut
  // through the globe towards the viewer
  vec3 toLogo = end - globeCenter;
  vec3 lateral = normalize(toLogo - toCamera * dot(toLogo, toCamera));
  vec3 scatter = jitter - toCamera * dot(jitter, toCamera);
  vec3 around = normalize(lateral + scatter * spread * 2.0);
  vec3 waypoint = globeCenter + (around * wide - toCamera * behind) * globeRadius;
  vec3 launched = start + normal * launch * globeRadius;
  float u = 1.0 - t;
  vec3 roundBack = u * u * u * start + 3.0 * u * u * t * launched + 3.0 * u * t * t * waypoint + t * t * t * end;

  vec3 path = mix(direct, roundBack, smoothstep(0.0, -0.3, facing));

  // Cells leaving the logo lift off towards the camera, straight along the
  // line of sight so they grow in place before heading off. Zero at the tile,
  // peaking a third of the way into the departure: 6.75 t^2 (1 - t) is 1 at t = 2/3
  path += (cameraPosition - end) * lift * 6.75 * t * t * (1.0 - t);

  // Repel the path from the globe: push it radially out to a clearance
  // radius, with a smooth max so cells skim round rather than bounce off.
  // Faded in over the first moments of flight, where the cell is on the surface
  vec3 offset = path - globeCenter;
  float d = max(length(offset), 1e-4);
  float clearance = globeRadius * 1.1;
  float k = globeRadius * 0.3;
  float h = clamp(0.5 + 0.5 * (clearance - d) / k, 0.0, 1.0);
  float pushed = mix(d, clearance, h) + k * h * (1.0 - h);
  return globeCenter + offset / d * mix(d, pushed, smoothstep(0.0, 0.1, t));
}

void main() {
  int c = int(chunk + 0.5);
  // Progress is stored negated while the chunk heads for the globe
  float stored = texelFetch(progress, ivec2(c % ${PROGRESS_TEXTURE_WIDTH}, c / ${PROGRESS_TEXTURE_WIDTH}), 0).r;
  float p = abs(stored);
  float lift = stored < 0.0 ? logoLift : 0.0;
  float t = flightTime(p);

  vec3 normal = rotation * center;
  vec3 start = globeCenter + normal * globeRadius;
  // Layers step towards the camera, at least slightly apart to avoid z-fighting
  vec3 tilePosition = vec3(tileCenter.xy, tileCenter.z * max(layerSpacing, 0.002));
  vec3 end = logoCenter + logoOffset + tilePosition * logoScale + (cameraPosition - logoCenter) * logoDepth;
  vec3 toCamera = normalize(cameraPosition - globeCenter);
  vec3 jitter = fract(sin(seed * vec3(12.9898, 78.233, 37.719)) * 43758.5453) - 0.5;
  vec3 path = flightPath(t, normal, start, end, toCamera, jitter, lift);

  // Morph the cell's outline from its shape on the globe to its tile
  vec3 onGlobe = rotation * (position - center) * globeRadius;
  vec3 inLogo = vec3(tile.xy - tileCenter.xy, 0.0) * logoScale;
  vec3 shape = mix(onGlobe, inLogo, t);

  // Motion blur: stretch the cell along its velocity by the distance it
  // covers while the shutter is open. Progress advances 1 / flightSeconds per
  // second, so the path a little earlier in the flight gives the velocity.
  // Chunks at rest (p = 0 or 1) stay sharp
  const float h = 0.01;
  vec3 velocity = p > 0.0 && p < 1.0
    ? (path - flightPath(flightTime(p - h), normal, start, end, toCamera, jitter, lift)) / (h * flightSeconds)
    : vec3(0.0);
  float speed = length(velocity);
  vec3 axis = speed > 1e-6 ? velocity / speed : vec3(0.0);
  // Capped at a few cell widths so the fastest cells read as dashes, not lines
  float streak = min(speed * shutter, length(shape) * 8.0);
  // Vertices ahead of the center move forwards, those behind move back
  vec3 p3 = path + shape + axis * dot(normalize(shape), axis) * streak * 0.5;

  vColor = fill;
  gl_Position = projectionMatrix * viewMatrix * vec4(p3, 1.0);
}
`;

const CELL_FRAGMENT_SHADER = /* glsl */ `
varying vec3 vColor;
void main() {
  gl_FragColor = vec4(vColor, 1.0);
}
`;

// Faint rim glow around the globe
const ATMOSPHERE_VERTEX_SHADER = /* glsl */ `
varying vec3 vNormal;
varying vec3 vView;
void main() {
  vec4 world = modelMatrix * vec4(position, 1.0);
  vNormal = normalize(mat3(modelMatrix) * normal);
  vView = normalize(cameraPosition - world.xyz);
  gl_Position = projectionMatrix * viewMatrix * world;
}
`;

const ATMOSPHERE_FRAGMENT_SHADER = /* glsl */ `
varying vec3 vNormal;
varying vec3 vView;
void main() {
  // Rendered on the back faces of a slightly larger sphere: |dot| falls from
  // ~0.38 where it meets the globe to 0 at its outer edge
  float glow = pow(clamp(abs(dot(vNormal, vView)) / 0.38, 0.0, 1.0), 2.0);
  gl_FragColor = vec4(0.35, 0.3, 0.8, 1.0) * glow * 0.5;
}
`;

// Legend: the active dataset's color ramp as a thin bar under its label below
// the globe, low on the left, or for categories their colors side by side.
// Drawn in the scene so it blooms like the cells
const RAMP_STOPS = 8;

const LEGEND_VERTEX_SHADER = /* glsl */ `
varying vec2 vUv;
void main() {
  vUv = uv;
  gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
}
`;

const LEGEND_FRAGMENT_SHADER = /* glsl */ `
uniform vec3 ramp[${RAMP_STOPS}];
// 0 for a continuous ramp over all the stops, else that many discrete colors
uniform float steps;
uniform float opacity;
varying vec2 vUv;
void main() {
  float x = clamp(vUv.x, 0.0, 1.0);
  if (steps > 0.0) {
    float s = x * steps;
    int i = int(min(floor(s), steps - 1.0));
    // A small gap between the colors
    float edge = fract(s);
    float alpha = edge < 0.08 && s > 1.0 ? 0.0 : 1.0;
    gl_FragColor = vec4(ramp[i], opacity * alpha);
    return;
  }
  float s = x * float(${RAMP_STOPS - 1});
  int i = int(min(floor(s), float(${RAMP_STOPS - 2})));
  vec3 color = mix(ramp[i], ramp[i + 1], s - float(i));
  gl_FragColor = vec4(color, opacity);
}
`;

// Full-screen background: the dark gradient, a faint nebula and three layers
// of twinkling stars, clumped by noise and shifted slightly as the globe
// turns so the nearer layers show a little parallax
const SKY_VERTEX_SHADER = /* glsl */ `
void main() {
  gl_Position = vec4(position.xy, 0.0, 1.0);
}
`;

const SKY_FRAGMENT_SHADER = /* glsl */ `
uniform vec2 resolution;
uniform float pixelRatio;
uniform float time;
// Parallax offset, in view heights
uniform vec2 drift;
// Scales the stars' core size and brightness
uniform float starSize;
uniform float starIntensity;

float hash(vec2 p) {
  vec3 p3 = fract(vec3(p.xyx) * 0.1031);
  p3 += dot(p3, p3.yzx + 33.33);
  return fract((p3.x + p3.y) * p3.z);
}

float noise(vec2 p) {
  vec2 i = floor(p);
  vec2 f = fract(p);
  vec2 u = f * f * (3.0 - 2.0 * f);
  return mix(mix(hash(i), hash(i + vec2(1.0, 0.0)), u.x), mix(hash(i + vec2(0.0, 1.0)), hash(i + vec2(1.0, 1.0)), u.x), u.y);
}

float fbm(vec2 p) {
  float value = 0.0;
  float amplitude = 0.5;
  for (int i = 0; i < 5; i++) {
    value += amplitude * noise(p);
    p *= 2.03;
    amplitude *= 0.5;
  }
  return value;
}

// At most one star per grid cell, cellsPerHeight cells across the view's
// height, a cell holding one with probability density
vec3 stars(vec2 uv, float cellsPerHeight, float density, float seed) {
  vec2 grid = uv * cellsPerHeight;
  vec2 id = floor(grid);
  float h = hash(id + seed);
  if (h > density) return vec3(0.0);
  vec2 center = 0.2 + 0.6 * vec2(hash(id + seed + 11.3), hash(id + seed + 27.1));
  // Distance from the star in pixels, with a Gaussian core of 0.35-0.9px
  float d = length(fract(grid) - center) / cellsPerHeight * resolution.y;
  float size = mix(0.35, 0.9, pow(hash(id + seed + 5.7), 3.0)) * pixelRatio * starSize;
  float core = exp(-d * d / (size * size));
  float twinkle = 0.75 + 0.25 * sin(time * (0.5 + 2.0 * hash(id + seed + 3.3)) + h * 40.0);
  vec3 tint = mix(vec3(0.75, 0.8, 1.0), vec3(1.0, 0.9, 0.75), hash(id + seed + 9.1));
  return tint * core * twinkle;
}

void main() {
  vec2 uv = gl_FragCoord.xy / resolution.y;
  // Same gradient as the page background, #000 at the bottom to #223 at the top
  vec3 color = vec3(0.133, 0.133, 0.2) * (gl_FragCoord.y / resolution.y);

  // Low frequency noise clumps the stars and lights a faint nebula
  float clump = smoothstep(0.3, 0.8, fbm(uv * 1.2 + drift * 0.2 + 7.0));
  float nebula = fbm(uv * 2.0 + drift * 0.3 + vec2(0.0, 3.0));
  color += vec3(0.25, 0.15, 0.45) * pow(nebula, 3.0) * 0.25 * clump;

  // Far to near: smaller, denser and fainter to sparser and brighter
  vec3 starlight = stars(uv + drift * 0.2, 90.0, 0.03 + 0.12 * clump, 1.0) * 0.3;
  starlight += stars(uv + drift * 0.5, 40.0, 0.03 + 0.1 * clump, 17.0) * 0.4;
  starlight += stars(uv + drift, 16.0, 0.06, 43.0) * 0.6;
  color += starlight * starIntensity;

  gl_FragColor = vec4(color, 1.0);
}
`;

// A narrow field of view keeps the globe round when it sits far off-axis in a
// wide banner. The distance keeps the visible height at ~5.4 world units
const FOV = 10;
const CAMERA_DISTANCE = 30;

// The globe sits further from the camera than the logo, each scaled to
// compensate so they look the same size. Only the flights between them show
// the difference: cells leave the distant globe as specks and grow as they
// approach the logo. Multiples of CAMERA_DISTANCE
const GLOBE_DISTANCE = 2.5;
const LOGO_DISTANCE = 0.7;

// Below this width (Docusaurus's mobile navbar) the homepage drops its tagline
const TAGLINE_MIN_WIDTH = 996;
// The tagline's inset from the left edge (4rem), matched by the globe's from
// the right
const TAGLINE_INSET = 64;
// Largest gap between the logo's layers when it sits off to the side of the
// view (the narrow side by side layout): seen at an angle, wider layer
// spacing smears the letters
const SIDE_LAYER_SPACING = 0.03;

type AppProps = {
  // Overlaid content (the homepage tagline) sits left of the logo on wide
  // screens (> TAGLINE_MIN_WIDTH): center the logo, and publish its left edge
  // as the --hero-logo-left CSS variable on the hero section so the overlay
  // can size itself to fit
  besideTagline?: boolean;
  // Pixels at the top of the view covered by a translucent navbar. The scene
  // is laid out below it but still drawn underneath
  insetTop?: number;
};

const App: React.FC<AppProps> = ({besideTagline = false, insetTop = 0}) => {
  const containerRef = useRef<HTMLDivElement | null>(null);
  const [status, setStatus] = useState<string | null>('Loading data…');
  // Arrow buttons: shown only while a dataset is on the globe
  const [arrowsVisible, setArrowsVisible] = useState(false);
  // Logo's extent on screen in pixels. On portrait screens the globe sits
  // below the logo, so the transition goes sideways and the arrows sit on the
  // line between the two (at height y), under the logo's edges
  const [logoBox, setLogoBox] = useState<{
    x: number;
    y: number;
    left: number;
    right: number;
    top: number;
    bottom: number;
    sideways: boolean;
  } | null>(null);
  // Globe's bottom center on screen, in pixels, for the dataset label
  const [globeBox, setGlobeBox] = useState<{x: number; bottom: number} | null>(null);
  // Dataset named by the label, which is hidden while datasets swap
  const [legendIndex, setLegendIndex] = useState(0);
  const [legendVisible, setLegendVisible] = useState(false);
  // Switch dataset: 1 = next (logo moves down, or right on portrait screens), -1 = previous
  const switchRef = useRef<((direction: 1 | -1) => void) | null>(null);

  useEffect(() => {
    const container = containerRef.current!;
    const renderer = new WebGLRenderer({antialias: true, alpha: true});
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    renderer.domElement.style.display = 'block';
    renderer.domElement.style.touchAction = 'pan-y';
    renderer.domElement.style.cursor = 'grab';
    container.appendChild(renderer.domElement);

    const scene = new Scene();
    const camera = new PerspectiveCamera(FOV, 1, 1, 1000);
    camera.position.set(0, 0, CAMERA_DISTANCE);

    const globe = new Group();
    // The custom shaders output sRGB colors as is, so no conversion on the
    // way to the screen, and the ocean's sRGB value is given as if linear
    renderer.outputColorSpace = LinearSRGBColorSpace;
    const ocean = new Mesh(
      new SphereGeometry(0.995, 96, 64),
      new MeshBasicMaterial({color: new Color().setHex(0x0d0f1f, LinearSRGBColorSpace)})
    );
    const atmosphere = new Mesh(
      new SphereGeometry(1.08, 96, 64),
      new ShaderMaterial({
        vertexShader: ATMOSPHERE_VERTEX_SHADER,
        fragmentShader: ATMOSPHERE_FRAGMENT_SHADER,
        side: BackSide,
        blending: AdditiveBlending,
        transparent: true,
        depthWrite: false
      })
    );
    globe.add(ocean, atmosphere);
    scene.add(globe);

    const sky = new Mesh(
      new PlaneGeometry(2, 2),
      new ShaderMaterial({
        uniforms: {
          resolution: {value: new Vector2()},
          pixelRatio: {value: 1},
          time: {value: 0},
          drift: {value: new Vector2()},
          starSize: {value: 1},
          starIntensity: {value: 1}
        },
        vertexShader: SKY_VERTEX_SHADER,
        fragmentShader: SKY_FRAGMENT_SHADER,
        depthTest: false,
        depthWrite: false
      })
    );
    // Drawn first, behind everything, whatever the camera
    sky.renderOrder = -1;
    sky.frustumCulled = false;
    scene.add(sky);
    const skyUniforms = (sky.material as ShaderMaterial).uniforms;

    const legend = new Mesh(
      new PlaneGeometry(1, 1),
      new ShaderMaterial({
        uniforms: {
          ramp: {value: Array.from({length: RAMP_STOPS}, () => new Vector3())},
          steps: {value: 0},
          opacity: {value: 0}
        },
        vertexShader: LEGEND_VERTEX_SHADER,
        fragmentShader: LEGEND_FRAGMENT_SHADER,
        transparent: true,
        depthWrite: false
      })
    );
    scene.add(legend);
    const legendUniforms = (legend.material as ShaderMaterial).uniforms;
    // Resample the ramp to a fixed number of evenly spaced stops
    const setLegendRamp = ({ramp, scale}: Dataset) => {
      // Categories: their colors as they are
      if (scale === 'categorical') {
        ramp.forEach((color, i) => legendUniforms.ramp.value[i].set(color[0] / 255, color[1] / 255, color[2] / 255));
        legendUniforms.steps.value = ramp.length;
        return;
      }
      legendUniforms.steps.value = 0;
      for (let i = 0; i < RAMP_STOPS; i++) {
        const s = (i / (RAMP_STOPS - 1)) * (ramp.length - 1);
        const j = Math.min(Math.floor(s), ramp.length - 2);
        const f = s - j;
        legendUniforms.ramp.value[i].set(
          (ramp[j][0] + (ramp[j + 1][0] - ramp[j][0]) * f) / 255,
          (ramp[j][1] + (ramp[j + 1][1] - ramp[j][1]) * f) / 255,
          (ramp[j][2] + (ramp[j + 1][2] - ramp[j][2]) * f) / 255
        );
      }
    };
    setLegendRamp(DATASETS[0]);
    // Whether the legend (bar and label) should be showing
    let legendShown = false;

    // Post-processing: a subtle bloom on the brightest cells and stars.
    // Multisampled so the cells keep their antialiasing
    const composer = new EffectComposer(renderer, new WebGLRenderTarget(1, 1, {type: HalfFloatType, samples: 4}));
    composer.addPass(new RenderPass(scene, camera));
    // Strength, radius and threshold are set per frame from the parameters
    const bloomPass = new UnrealBloomPass(new Vector2(1, 1), 0, 0, 0);
    composer.addPass(bloomPass);

    // Start fetching the data straight away, it downloads while the rest of
    // the scene (logo tiles especially) is set up
    const dataFilePromise = openDataFile();
    const firstColumnsPromise = dataFilePromise.then(file => file.readColumns(['cell', 'chunk', DATASETS[0].column!]));
    // Handled when awaited below, don't report as unhandled meanwhile
    firstColumnsPromise.catch(() => {});

    const logo = createLogoTiles();

    const uniforms = {
      rotation: {value: new Matrix3()},
      globeCenter: {value: new Vector3()},
      globeRadius: {value: 1},
      logoCenter: {value: new Vector3()},
      logoScale: {value: 1},
      stagger: {value: 0},
      launch: {value: 0},
      behind: {value: 0},
      wide: {value: 0},
      spread: {value: 0},
      logoLift: {value: 0},
      layerSpacing: {value: 0},
      logoDepth: {value: 0},
      flightSeconds: {value: 1},
      shutter: {value: 0}
    };
    // The cells, shared by all datasets, created once the first has loaded
    type Layer = {
      mesh: Mesh;
      logoOffset: Vector3;
      // Per-chunk state
      centers: Float32Array;
      count: number;
      target: Uint8Array; // 0 = globe, 1 = logo
      hidden: Float32Array; // seconds spent facing away
      progress: Float32Array;
      // Cells per chunk, and in total
      sizes: Uint32Array;
      cellCount: number;
      // Texture data: progress, negated while heading for the globe
      texels: Float32Array;
      texture: DataTexture;
    };
    let layer: Layer | null = null;
    // Whether the cells' globe positions have been computed, see computeGlobeAsync.
    // Until then they stay in the logo
    let globeReady = false;
    // Each dataset's colors for the cells, created as each finishes loading
    const fills: (BufferAttribute | null)[] = DATASETS.map(() => null);
    let active = 0;
    // Where the dataset cycle is up to, and for how long it has been there
    let phase: 'globe' | 'gather' | 'hold' | 'dropOut' | 'gap' | 'dropIn' = 'globe';
    let phaseTime = 0;
    // Dataset the current transition is heading to, and which way it moves
    let incomingIndex = 0;
    let direction: 1 | -1 = 1;
    // Globe radius as it appears at the reference distance, for drag speed
    let apparentRadius = 1;
    // Axis the logo moves along to leave the view (0 = x, 1 = y), and how far
    let dropAxis = 1;
    let dropDistance = 1;
    // Whether the logo is off to the side of the view, see SIDE_LAYER_SPACING
    let logoToSide = false;
    // Move a logo along the drop axis. Negative amounts move it down, or
    // right when sideways, so the logo leaves the way its arrow points
    const setDrop = (offset: Vector3, amount: number) =>
      offset.set(0, 0, 0).setComponent(dropAxis, dropAxis === 0 ? -amount : amount);

    // Globe on the right, logo on the left (stacked vertically on portrait
    // screens), laid out as they appear on the z = 0 plane then moved in depth
    const layout = () => {
      const width = container.clientWidth;
      const height = container.clientHeight;
      renderer.setSize(width, height);
      composer.setPixelRatio(renderer.getPixelRatio());
      composer.setSize(width, height);
      renderer.getDrawingBufferSize(skyUniforms.resolution.value);
      skyUniforms.pixelRatio.value = renderer.getPixelRatio();
      camera.aspect = width / height;
      camera.updateProjectionMatrix();
      // The whole view, in world units on the z = 0 plane
      const halfH = Math.tan((FOV / 2) * (Math.PI / 180)) * CAMERA_DISTANCE;
      const halfW = halfH * camera.aspect;
      const pixelsPerUnit = height / (2 * halfH);
      // The area below the inset, which the layout fills
      const frameHeight = Math.max(height - insetTop, 1);
      const frameHalfH = frameHeight / 2 / pixelsPerUnit;
      const frameY = -insetTop / 2 / pixelsPerUnit;
      const portrait = width < frameHeight;
      // Apparent sizes: the globe's radius and the logo's width
      let globeX: number;
      let globeY: number;
      let logoX: number;
      let logoY: number;
      let logoWidth: number;
      logoToSide = false;
      if (portrait) {
        // Logo above the globe, sized for half the frame each, with the globe
        // then moved up to halve the gap between them
        [logoX, logoY] = [0, frameY + frameHalfH / 2];
        apparentRadius = Math.min(halfW, frameHalfH / 2) * 0.8;
        logoWidth = Math.min(halfW * 1.6, ((frameHalfH / 2) * 1.4) / logo.height);
        const logoBottom = logoY - (logoWidth * logo.height) / 2;
        const gap = logoBottom - (frameY - frameHalfH / 2 + apparentRadius);
        [globeX, globeY] = [0, logoBottom - gap / 2 - apparentRadius];
      } else if (besideTagline && width > TAGLINE_MIN_WIDTH) {
        // Logo in the middle of the view and the globe at its right edge, inset
        // as far as the overlaid content on the left (the Tagline's 4rem, it
        // sizes itself to end short of the logo). The globe's diameter is
        // capped at 70% of the frame's height and the logo's height at 40%,
        // both shrinking to fit between them on narrower screens
        const margin = TAGLINE_INSET / pixelsPerUnit;
        apparentRadius = Math.min(frameHalfH * 0.7, ((halfW - margin) / 3) * 0.8);
        const gap = apparentRadius * 0.5;
        [globeX, globeY] = [halfW - margin - apparentRadius, frameY];
        [logoX, logoY] = [0, frameY];
        logoWidth = Math.min((frameHalfH * 0.8) / logo.height, 2 * (globeX - apparentRadius - gap));
      } else {
        // Side by side, each in half the view
        logoToSide = true;
        const quarter = halfW / 2;
        [globeX, globeY, logoX, logoY] = [quarter, frameY, -quarter, frameY];
        // Capped as above, and narrower than the half: the logo's layers step
        // towards the camera (layerSpacing), so it looks wider than it is
        apparentRadius = Math.min(quarter * 0.8, frameHalfH * 0.7);
        logoWidth = Math.min(quarter * 1.3, (frameHalfH * 0.8) / logo.height);
      }

      // Moving an object to k times the camera distance and scaling it (and
      // its offset from the view axis) by k leaves it looking the same
      const globeK = GLOBE_DISTANCE;
      const logoK = LOGO_DISTANCE;
      const globeZ = CAMERA_DISTANCE * (1 - globeK);
      const logoZ = CAMERA_DISTANCE * (1 - logoK);

      const radius = apparentRadius * globeK;
      globe.position.set(globeX * globeK, globeY * globeK, globeZ);
      // Legend bar under the dataset label (see globeBox), at the reference
      // distance: 3px tall, 36px below the globe
      legend.position.set(globeX, globeY - apparentRadius - 36 / pixelsPerUnit, 0);
      legend.scale.set(apparentRadius * 0.5, 3 / pixelsPerUnit, 1);
      setGlobeBox({
        x: (globeX + halfW) * pixelsPerUnit,
        bottom: (halfH - globeY + apparentRadius) * pixelsPerUnit
      });
      globe.scale.setScalar(radius);
      uniforms.globeCenter.value.copy(globe.position);
      uniforms.globeRadius.value = radius;

      const logoScale = logoWidth * logoK;
      container
        .closest('section')
        ?.style.setProperty('--hero-logo-left', `${(logoX - logoWidth / 2 + halfW) * pixelsPerUnit}px`);
      uniforms.logoCenter.value.set(logoX * logoK, logoY * logoK, logoZ);
      uniforms.logoScale.value = logoScale;
      // Visible half extent at the logo's depth, plus the logo's own half
      // extent, from wherever it sits. Sideways on portrait screens, where
      // dropping would send the logo through the globe
      dropAxis = portrait ? 0 : 1;
      dropDistance = portrait
        ? (halfW + Math.abs(logoX)) * logoK + logoScale / 2
        : (halfH + Math.abs(logoY)) * logoK + (logoScale * logo.height) / 2;

      // Logo position in pixels, for placing the arrow buttons
      const halfWidth = logoScale / logoK / 2;
      const halfHeight = halfWidth * logo.height;
      setLogoBox({
        x: (logoX + halfW) * pixelsPerUnit,
        // Portrait layout: halfway between the logo and the globe
        y: (halfH - (logoY - (logoWidth * logo.height) / 2 + globeY + apparentRadius) / 2) * pixelsPerUnit,
        left: (logoX + halfW - halfWidth) * pixelsPerUnit,
        right: (logoX + halfW + halfWidth) * pixelsPerUnit,
        top: (halfH - logoY - halfHeight) * pixelsPerUnit,
        bottom: (halfH - logoY + halfHeight) * pixelsPerUnit,
        sideways: portrait
      });
    };
    layout();
    const resizeObserver = new ResizeObserver(layout);
    resizeObserver.observe(container);

    // Rotation state: dragging sets longitude/latitude directly, releasing
    // keeps some momentum, and auto-rotation eases back in after a pause. The
    // globe spins from the start, but the first grab holds it still for longer
    let longitude = INITIAL_LONGITUDE;
    let latitude = INITIAL_LATITUDE;
    let velocity = 0;
    let lastInteraction = -Infinity;
    let rotateFrom = -Infinity;
    let drag: {x: number; y: number; time: number} | null = null;

    const onPointerDown = (e: PointerEvent) => {
      drag = {x: e.clientX, y: e.clientY, time: performance.now()};
      if (rotateFrom === -Infinity) rotateFrom = drag.time + INITIAL_ROTATE_DELAY;
      velocity = 0;
      renderer.domElement.setPointerCapture(e.pointerId);
      renderer.domElement.style.cursor = 'grabbing';
    };
    const onPointerMove = (e: PointerEvent) => {
      if (!drag) return;
      const now = performance.now();
      // Degrees per pixel so the surface roughly follows the pointer
      const radiusPx =
        (apparentRadius / (CAMERA_DISTANCE * Math.tan((FOV * Math.PI) / 360))) * (container.clientHeight / 2);
      const scale = 180 / Math.PI / radiusPx;
      const dLon = -(e.clientX - drag.x) * scale;
      longitude += dLon;
      latitude = Math.max(-40, Math.min(40, latitude + (e.clientY - drag.y) * scale));
      velocity = (dLon / Math.max(now - drag.time, 1)) * 1000;
      drag = {x: e.clientX, y: e.clientY, time: now};
      lastInteraction = now;
    };
    const onPointerUp = () => {
      drag = null;
      lastInteraction = performance.now();
      renderer.domElement.style.cursor = 'grab';
    };
    renderer.domElement.addEventListener('pointerdown', onPointerDown);
    renderer.domElement.addEventListener('pointermove', onPointerMove);
    renderer.domElement.addEventListener('pointerup', onPointerUp);
    renderer.domElement.addEventListener('pointercancel', onPointerUp);

    const rotation = new Matrix4();
    const tilt = new Matrix4();
    const normal = new Vector3();
    const view = new Vector3();
    // Pick each chunk's destination from which way its center faces (or send
    // everything to the logo while gathering), then move it towards that at a
    // constant rate. A chunk always completes its flight, so nothing is left
    // hanging when the globe stops. Returns whether every chunk is in the logo
    const updateChunks = (state: Layer, dt: number, gather: boolean): boolean => {
      const {flightSeconds, leaveAngle, leaveDelay, stagger} = PARAMETERS;
      const step = dt / flightSeconds;
      // Share of a chunk's cells that have landed in the logo at progress p,
      // with cells' staggered starts (see flightTime) spread evenly
      const landed = (p: number) =>
        stagger > 0 ? Math.min(Math.max((p * (1 + stagger) - 1) / stagger, 0), 1) : +(p >= 1);
      // Facing is cos(90° + angle past the limb)
      const leaveFacing = -Math.sin((leaveAngle * Math.PI) / 180);
      let changed = false;
      let allInLogo = true;
      for (let c = 0; c < state.count; c++) {
        // Chunk ids are sparse (see prepare.sql)
        if (state.sizes[c] === 0) continue;
        normal.fromArray(state.centers, c * 3).applyMatrix3(uniforms.rotation.value);
        view
          .copy(camera.position)
          .sub(uniforms.globeCenter.value)
          .addScaledVector(normal, -uniforms.globeRadius.value)
          .normalize();
        const facing = normal.dot(view);
        if (gather) {
          state.target[c] = 1;
        } else if (facing > RETURN_FACING) {
          state.target[c] = 0;
          state.hidden[c] = 0;
        } else if (facing < leaveFacing) {
          state.hidden[c] += dt;
          if (state.hidden[c] >= leaveDelay) state.target[c] = 1;
        }

        const current = state.progress[c];
        const next = state.target[c] ? Math.min(current + step, 1) : Math.max(current - step, 0);
        state.progress[c] = next;
        // Cells landing push the logo forwards, cells leaving push it back
        logoImpulse += ((landed(next) - landed(current)) * state.sizes[c]) / state.cellCount;
        const texel = state.target[c] ? next : -next;
        if (texel !== state.texels[c]) {
          state.texels[c] = texel;
          changed = true;
        }
        if (next < 1) allInLogo = false;
      }
      if (changed) state.texture.needsUpdate = true;
      return allInLogo;
    };

    const enter = (p: typeof phase) => {
      phase = p;
      phaseTime = 0;
      syncArrows();
      // The legend fades out while the logo drops out and back in once the
      // next dataset has arrived
      showLegend(phase === 'globe' || phase === 'gather' || phase === 'hold');
    };
    const showLegend = (shown: boolean) => {
      legendShown = shown;
      setLegendVisible(shown);
    };
    // Arrows need a dataset on the globe and another one to switch to
    const syncArrows = () => setArrowsVisible(phase === 'globe' && globeReady && fills.filter(Boolean).length > 1);

    // Start a transition to the neighboring dataset, if it has loaded
    const switchDataset = (towards: 1 | -1) => {
      const target = (active + towards + DATASETS.length) % DATASETS.length;
      if (phase !== 'globe' || !globeReady || target === active || !fills[target]) return;
      incomingIndex = target;
      direction = towards;
      enter('gather');
    };
    switchRef.current = switchDataset;

    // Advance the dataset cycle, see GLOBE_SECONDS
    const updateCycle = (dt: number) => {
      if (!layer) return;
      phaseTime += dt;

      if (phase === 'globe') {
        // Hold everything in the logo until the globe is ready
        if (!globeReady) {
          phaseTime = 0;
          return;
        }
        updateChunks(layer, dt, false);
        // phaseTime restarts whenever a dataset lands, whether switched
        // automatically or by the user
        const idle = !drag && performance.now() - lastInteraction > IDLE_SECONDS * 1000;
        if (phaseTime > GLOBE_SECONDS && idle) switchDataset(1);
      } else if (phase === 'gather') {
        if (updateChunks(layer, dt, true)) enter('hold');
      } else if (phase === 'hold') {
        if (phaseTime > HOLD_SECONDS) enter('dropOut');
      } else if (phase === 'dropOut') {
        const t = Math.min(phaseTime / DROP_OUT_SECONDS, 1);
        setDrop(layer.logoOffset, -direction * dropDistance * easeInBack(t));
        if (t === 1) {
          // Out of view, recolor the cells with the new dataset, still
          // gathered in the logo, and bring it round from the side the old one
          // left from. Far side chunks count as already hidden so they stay
          active = incomingIndex;
          setLegendRamp(DATASETS[active]);
          setLegendIndex(active);
          layer.mesh.geometry.setAttribute('fill', fills[active]!);
          layer.hidden.fill(PARAMETERS.leaveDelay);
          setDrop(layer.logoOffset, direction * dropDistance);
          enter('gap');
        }
      } else if (phase === 'gap') {
        if (phaseTime > GAP_SECONDS) enter('dropIn');
      } else if (phase === 'dropIn') {
        const t = Math.min(phaseTime / DROP_IN_SECONDS, 1);
        setDrop(layer.logoOffset, direction * dropDistance * (1 - springIn(t)));
        if (t === 1) {
          setDrop(layer.logoOffset, 0);
          enter('globe');
        }
      }
    };
    // Logo spring along the line of sight: displacement as a fraction of the
    // logo's distance from the camera (positive is closer), and its velocity
    let logoDepth = 0;
    let logoVelocity = 0;
    // Share of the dataset's cells landed (positive) or left (negative) since
    // the last frame
    let logoImpulse = 0;

    let lastFrame = performance.now();
    let frame = requestAnimationFrame(function animate(now) {
      const dt = Math.min((now - lastFrame) / 1000, 0.1);
      lastFrame = now;
      if (!drag) {
        // Auto-rotation eases in over 2s, once past both delays
        const since = Math.min(now - lastInteraction - AUTO_ROTATE_DELAY, now - rotateFrom);
        const idle = Math.min(Math.max(since / 2000, 0), 1);
        velocity *= Math.exp(-3 * dt);
        longitude += (velocity - AUTO_ROTATE_SPEED * idle) * dt;
      }
      // Bring (longitude, latitude) to face the camera
      rotation.makeRotationY((-longitude * Math.PI) / 180);
      tilt.makeRotationX((latitude * Math.PI) / 180);
      rotation.premultiply(tilt);
      ocean.quaternion.setFromRotationMatrix(rotation);
      uniforms.rotation.value.setFromMatrix4(rotation);
      skyUniforms.time.value = now / 1000;
      // Fade the legend bar in and out over ~0.3s
      const legendOpacity = legendUniforms.opacity.value;
      legendUniforms.opacity.value = legendShown
        ? Math.min(legendOpacity + dt / 0.3, 1)
        : Math.max(legendOpacity - dt / 0.3, 0);
      skyUniforms.drift.value.set(-longitude, latitude).multiplyScalar(0.002);
      const {
        stagger,
        launch,
        behind,
        wide,
        spread,
        logoLift,
        layerSpacing,
        flightSeconds,
        shutter,
        bloom,
        bloomRadius,
        bloomThreshold,
        starSize,
        starIntensity
      } = PARAMETERS;
      skyUniforms.starSize.value = starSize;
      skyUniforms.starIntensity.value = starIntensity;
      uniforms.flightSeconds.value = flightSeconds;
      uniforms.shutter.value = shutter;
      bloomPass.strength = bloom;
      bloomPass.radius = bloomRadius;
      bloomPass.threshold = bloomThreshold;
      bloomPass.enabled = bloom > 0;
      uniforms.stagger.value = stagger;
      uniforms.launch.value = launch;
      uniforms.behind.value = behind;
      uniforms.wide.value = wide;
      uniforms.spread.value = spread;
      uniforms.logoLift.value = logoLift;
      uniforms.layerSpacing.value = logoToSide ? Math.min(layerSpacing, SIDE_LAYER_SPACING) : layerSpacing;
      updateCycle(dt);

      // Mass on a damped hardening spring, m x'' = -k x (1 + (x/r)^2) - c x',
      // kicked by landing and leaving cells: soft for small displacements,
      // increasingly stiff past r. Integrated in small fixed steps so a stiff
      // spring stays stable through long frames
      const {logoPush, logoMass, springStiffness, springDamping, springRange} = PARAMETERS;
      logoVelocity += (logoImpulse * logoPush) / logoMass;
      logoImpulse = 0;
      const substeps = Math.ceil(dt / (1 / 240));
      for (let i = 0; i < substeps; i++) {
        const h = dt / substeps;
        const stretch = springRange > 0 ? logoDepth / springRange : 0;
        const spring = springStiffness * logoDepth * (1 + stretch * stretch);
        logoVelocity += ((-spring - springDamping * logoVelocity) / logoMass) * h;
        logoDepth = Math.min(Math.max(logoDepth + logoVelocity * h, -0.3), 0.3);
      }
      uniforms.logoDepth.value = logoDepth;

      composer.render(dt);
      frame = requestAnimationFrame(animate);
    });

    const createLayer = (geometry: BufferGeometry, cells: ReturnType<typeof createCellGeometry>): Layer => {
      const {chunkSizes, chunkCount} = cells;
      const rows = Math.ceil(chunkCount / PROGRESS_TEXTURE_WIDTH);
      const progress = new Float32Array(chunkCount);
      const texels = new Float32Array(PROGRESS_TEXTURE_WIDTH * rows);
      const texture = new DataTexture(texels, PROGRESS_TEXTURE_WIDTH, rows, RedFormat, FloatType);
      texture.needsUpdate = true;
      const logoOffset = new Vector3();
      const mesh = new Mesh(
        geometry,
        new ShaderMaterial({
          uniforms: {...uniforms, progress: {value: texture}, logoOffset: {value: logoOffset}},
          vertexShader: CELL_VERTEX_SHADER,
          fragmentShader: CELL_FRAGMENT_SHADER,
          // Cells turn over mid-flight
          side: DoubleSide
        })
      );
      mesh.frustumCulled = false;
      scene.add(mesh);
      return {
        mesh,
        logoOffset,
        // Filled in once the globe is ready
        centers: new Float32Array(chunkCount * 3),
        count: chunkCount,
        target: new Uint8Array(chunkCount),
        hidden: new Float32Array(chunkCount),
        progress,
        sizes: chunkSizes,
        cellCount: cells.seed.length / 5,
        texels,
        texture
      };
    };

    let cancelled = false;
    (async () => {
      const dataFile = await dataFilePromise;
      const first = DATASETS[0].column!;
      const {cell, chunk, [first]: firstValues} = await firstColumnsPromise;
      if (cancelled) return;

      // Start the globe geometry, the slow part, off the main thread. The data
      // file uses the v0 index, so migrate its cells first
      const globePromise = computeGlobeAsync(BigUint64Array.from(cell, migrate));

      // Meanwhile show the first dataset as a dataset switch shows the next:
      // gathered in the logo, which springs in from above, then onto the
      // globe once it's ready. Far side chunks count as already hidden so
      // they stay in the logo
      const cells = createCellGeometry(chunk, logo);
      fills[0] = createFill(firstValues, DATASETS[0], cells.seed);
      cells.geometry.setAttribute('fill', fills[0]);
      const created = createLayer(cells.geometry, cells);
      created.progress.fill(1);
      created.texels.fill(1);
      created.target.fill(1);
      created.hidden.fill(PARAMETERS.leaveDelay);
      direction = 1;
      setDrop(created.logoOffset, dropDistance);
      layer = created;
      setStatus(null);
      enter('dropIn');

      globePromise.then(globe => {
        if (cancelled) return;
        created.centers = setGlobe(cells.geometry, chunk, cells.chunkCount, globe);
        globeReady = true;
        syncArrows();
      });

      // Then the other datasets' colors, in the background
      for (let i = 1; i < DATASETS.length && !cancelled; i++) {
        const {column, fromChunk} = DATASETS[i];
        const values = column ? (await dataFile.readColumns([column]))[column] : chunk.map(fromChunk!);
        if (cancelled) return;
        fills[i] = createFill(values, DATASETS[i], cells.seed);
        syncArrows();
      }
    })().catch(e => setStatus((e as Error).message));

    return () => {
      cancelled = true;
      cancelAnimationFrame(frame);
      resizeObserver.disconnect();
      scene.traverse(object => {
        if (object instanceof Mesh) {
          object.geometry.dispose();
          object.material.dispose();
        }
      });
      layer?.texture.dispose();
      switchRef.current = null;
      composer.dispose();
      bloomPass.dispose();
      renderer.dispose();
      renderer.domElement.remove();
    };
  }, [besideTagline, insetTop]);

  return (
    <div
      style={{
        position: 'absolute',
        height: '100%',
        width: '100%',
        top: 0,
        left: 0,
        overflow: 'hidden',
        background: 'linear-gradient(0, #000, #223)'
      }}
    >
      <div ref={containerRef} style={{position: 'absolute', inset: 0}} />
      {globeBox && (
        <div
          style={{
            position: 'absolute',
            left: globeBox.x,
            top: globeBox.bottom + 10,
            transform: 'translateX(-50%)',
            color: '#aab',
            fontFamily: 'sans-serif',
            fontSize: '12px',
            letterSpacing: '0.1em',
            textTransform: 'uppercase',
            pointerEvents: 'none',
            opacity: legendVisible ? 1 : 0,
            transition: 'opacity 300ms'
          }}
        >
          {DATASETS[legendIndex].label}
        </div>
      )}
      {logoBox && (
        <>
          <ArrowButton
            direction={logoBox.sideways ? 'left' : 'up'}
            visible={arrowsVisible}
            onClick={() => switchRef.current?.(-1)}
            style={
              logoBox.sideways
                ? {left: logoBox.left, top: logoBox.y, transform: 'translate(-50%, -50%)'}
                : {left: logoBox.x, top: logoBox.top - 48, transform: 'translate(-50%, -100%)'}
            }
          />
          <ArrowButton
            direction={logoBox.sideways ? 'right' : 'down'}
            visible={arrowsVisible}
            onClick={() => switchRef.current?.(1)}
            style={
              logoBox.sideways
                ? {left: logoBox.right, top: logoBox.y, transform: 'translate(-50%, -50%)'}
                : {left: logoBox.x, top: logoBox.bottom + 48, transform: 'translateX(-50%)'}
            }
          />
        </>
      )}
      {status && (
        <div
          style={{
            position: 'absolute',
            bottom: '16px',
            right: '16px',
            color: '#889',
            fontFamily: 'sans-serif',
            fontSize: '12px'
          }}
        >
          {status}
        </div>
      )}
    </div>
  );
};

const CHEVRONS = {
  up: 'M2 9.5 L7 4.5 L12 9.5',
  down: 'M2 4.5 L7 9.5 L12 4.5',
  left: 'M9.5 2 L4.5 7 L9.5 12',
  right: 'M4.5 2 L9.5 7 L4.5 12'
};

function ArrowButton({
  direction,
  visible,
  onClick,
  style
}: {
  direction: 'up' | 'down' | 'left' | 'right';
  visible: boolean;
  onClick: () => void;
  style: React.CSSProperties;
}) {
  return (
    <button
      onClick={onClick}
      aria-label={direction === 'up' || direction === 'left' ? 'Previous dataset' : 'Next dataset'}
      style={{
        position: 'absolute',
        width: '32px',
        height: '32px',
        padding: 0,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: '50%',
        border: '1px solid rgba(170, 170, 204, 0.4)',
        background: 'rgba(20, 22, 40, 0.6)',
        color: '#ccd',
        cursor: 'pointer',
        opacity: visible ? 1 : 0,
        pointerEvents: visible ? 'auto' : 'none',
        transition: 'opacity 300ms',
        ...style
      }}
    >
      <svg width="14" height="14" viewBox="0 0 14 14" aria-hidden>
        <path
          d={CHEVRONS[direction]}
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    </button>
  );
}

export default App;

export async function renderToDOM(container: HTMLDivElement) {
  const root = createRoot(container);
  root.render(<App />);
}
