import React, { useState, useMemo, useEffect, useRef } from "react";
import { createRoot } from "react-dom/client";
import "maplibre-gl/dist/maplibre-gl.css";
import { Map as Maplibre, useControl } from "react-map-gl/maplibre";
import { MapboxOverlay as DeckOverlay } from "@deck.gl/mapbox";
import { SolidPolygonLayer } from "@deck.gl/layers";
import { cellToBoundary } from "a5/core/cell";
import { uncompact } from "a5/core/compact";
import { parquetRead } from "hyparquet";
import type { LonLat } from "a5/core/coordinate-systems";

// Generated by examples/cli/country-polygons:
//   yarn install && node index.js --resolution 5
const COMPACTED_DATA = "/data/country-polygons-compacted.parquet";
const RESOLUTION = 8;

const INITIAL_VIEW_STATE = {
  longitude: 0,
  latitude: 20,
  zoom: 2,
  minZoom: 2,
  maxZoom: 3,
  pitch: 0,
  bearing: 0,
};

type CellPoly = {
  boundary: LonLat[];
  color: [number, number, number, number];
  // Per-cell normal perturbation (in common space). Length ~0.6, deterministic from cell id.
  normal: [number, number, number];
};

function cellBoundary(id: bigint): LonLat[] {
  return cellToBoundary(id, { closedRing: true, segments: 1 }) as LonLat[];
}

/**
 * 7-colour cartographic palette tuned for a dark basemap. Country assignment
 * uses Natural Earth's precomputed `mapcolor7` property — a valid 7-coloring
 * of the country adjacency graph — so we just index this palette by
 * `mapcolor7 - 1`.
 */
const PALETTE: [number, number, number, number][] = [
  [45, 80, 4, 220], // dark green
  [145, 183, 217, 220], //  light blue
  [118, 176, 66, 220], // light green
  [4, 45, 80, 220], // deep navy
  [220, 227, 222, 220], // pale grey
  [82, 128, 35, 220], // olive green
  [8, 89, 159, 220], // blue
];

const FALLBACK_COLOR: [number, number, number, number] = [120, 120, 120, 220];

/** Build a 32-bit hash from a 64-bit cell id, with an optional salt to derive multiple values. */
function cellHash(id: bigint, salt: number): number {
  const lo = Number(id & 0xffffffffn);
  const hi = Number((id >> 32n) & 0xffffffffn);
  let h =
    (lo ^ Math.imul(hi, 0x9e3779b1) ^ Math.imul(salt | 0, 0x85ebca6b)) >>> 0;
  h = Math.imul(h ^ (h >>> 16), 0x85ebca6b) >>> 0;
  h = Math.imul(h ^ (h >>> 13), 0xc2b2ae35) >>> 0;
  return (h ^ (h >>> 16)) >>> 0;
}

/** Per-cell lightness jitter hashed from the cell id, so adjacent cells differ slightly. */
function jitterByCell(
  color: [number, number, number, number],
  id: bigint,
): [number, number, number, number] {
  // Multiplicative factor in [1.0, 1.22] — only ever lightens.
  const f = 1.0 + (cellHash(id, 0) / 0xffffffff) * 0.22;
  return [
    Math.max(0, Math.min(255, Math.round(color[0] * f))),
    Math.max(0, Math.min(255, Math.round(color[1] * f))),
    Math.max(0, Math.min(255, Math.round(color[2] * f))),
    color[3],
  ];
}

/** Random unit-direction normal for the cell — full random direction so most cells
 * are misaligned with the view, and only a few line up at any one time (twinkle). */
function perturbForCell(id: bigint): [number, number, number] {
  const u = cellHash(id, 1) / 0xffffffff;
  const v = cellHash(id, 2) / 0xffffffff;
  const phi = u * Math.PI * 2;
  const cosTheta = v * 2 - 1;
  const sinTheta = Math.sqrt(Math.max(0, 1 - cosTheta * cosTheta));
  return [sinTheta * Math.cos(phi), sinTheta * Math.sin(phi), cosTheta];
}

// Custom uniform block shared by both layers — lets us animate the light
// direction from the host app without recompiling shaders.
const globeLightModule = {
  name: "globeLight",
  vs: /* glsl */ `
uniform globeLightUniforms {
  vec3 dir;
} globeLight;
  `,
  fs: /* glsl */ `
uniform globeLightUniforms {
  vec3 dir;
} globeLight;
  `,
  uniformTypes: { dir: "vec3<f32>" },
} as any;

// Default light direction (normalized) — used when no orbit is animating yet.
const DEFAULT_LIGHT_DIR: [number, number, number] = [0.6489, 0.4867, 0.584];

/** A grid of 5°×5° quads tiling the globe. deck.gl's polygon tessellator can't
 * subdivide a single world-sized polygon onto the sphere, so we hand it many
 * small ones instead. */
const GLOBE_PATCHES: { polygon: [number, number][] }[] = (() => {
  const step = 5;
  const out: { polygon: [number, number][] }[] = [];
  for (let lat = -90; lat < 90; lat += step) {
    for (let lon = -180; lon < 180; lon += step) {
      out.push({
        polygon: [
          [lon, lat],
          [lon + step, lat],
          [lon + step, lat + step],
          [lon, lat + step],
        ],
      });
    }
  }
  return out;
})();

/**
 * Renders a near-opaque world-spanning polygon whose alpha is driven by the
 * unlit-hemisphere Lambert term, so the basemap reads as a shaded sphere
 * instead of a flat texture. Sits beneath the cells.
 */
class GlobeShadowLayer extends SolidPolygonLayer<{ polygon: number[][] }> {
  static layerName = "GlobeShadowLayer";
  static defaultProps = {
    ...SolidPolygonLayer.defaultProps,
    lightDir: { type: "array", value: DEFAULT_LIGHT_DIR },
  } as any;

  getShaders(type?: any) {
    const shaders = super.getShaders(type);
    return {
      ...shaders,
      modules: [...shaders.modules, globeLightModule],
      inject: {
        ...(shaders.inject ?? {}),
        "vs:#decl": /* glsl */ `out float vShadowLambert;`,
        "vs:DECKGL_FILTER_COLOR": /* glsl */ `
vec3 radial = normalize(geometry.position.xyz);
// Unclamped — fragment shader needs the negative side to place the rim band.
vShadowLambert = dot(radial, globeLight.dir);
        `,
        "fs:#decl": /* glsl */ `in float vShadowLambert;`,
        "fs:DECKGL_FILTER_COLOR": /* glsl */ `
float l = vShadowLambert;
// Crisper-than-Lambert step centred on the terminator (~12° wide).
float night = smoothstep(0.10, -0.05, l);
// Narrow refraction band, slightly biased to the lit side.
float rim = exp(-pow((l - 0.03) * 22.0, 2.0)) * 0.1;
vec3 rimColor = vec3(1.0, 0.55, 0.32);
vec3 rgb = rimColor * rim * (1.0 - night * 0.7);
float a = clamp(night * 0.88 + rim * 0.18, 0.0, 0.94);
color = vec4(rgb, a);
        `,
      },
    };
  }

  draw(params: any) {
    const dir = (this.props as any).lightDir;
    // SolidPolygonLayer keeps multiple models (top / side / wireframe). Push
    // the uniform to all of them.
    const models: any[] = (this.state as any).models ?? [];
    for (const m of models) {
      m?.shaderInputs?.setProps({ globeLight: { dir } });
    }
    super.draw(params);
  }
}

/**
 * SolidPolygonLayer extension: per-cell normal perturbation + view-dependent
 * specular highlight. Produces a "disco-ball" twinkle on a globe basemap as
 * the camera rotates.
 */
class TwinklePolygonLayer extends SolidPolygonLayer<CellPoly> {
  static layerName = "TwinklePolygonLayer";
  static defaultProps = {
    ...SolidPolygonLayer.defaultProps,
    getNormal: { type: "accessor", value: [0, 0, 1] },
    lightDir: { type: "array", value: DEFAULT_LIGHT_DIR },
  } as any;

  initializeState(context: any) {
    super.initializeState(context);
    this.getAttributeManager()!.add({
      cellNormals: {
        size: 3,
        stepMode: "dynamic",
        accessor: "getNormal",
        defaultValue: [0, 0, 1],
      },
    });
  }

  getShaders(type?: any) {
    const shaders = super.getShaders(type);
    return {
      ...shaders,
      modules: [...shaders.modules, globeLightModule],
      inject: {
        ...(shaders.inject ?? {}),
        "vs:#decl": /* glsl */ `
in vec3 cellNormals;
out float vSpec;
out float vLambert;
        `,
        "vs:DECKGL_FILTER_COLOR": /* glsl */ `
// Per-cell specular twinkle. Blinn-Phong: light reflects off the perturbed
// cell normal toward the eye, so highlights move as the light orbits.
vec3 radial = normalize(geometry.position.xyz);
vec3 N = normalize(cellNormals + 0.15 * radial);
vec3 V = normalize(project.cameraPosition - geometry.position.xyz);
vec3 L = normalize(globeLight.dir);
vec3 H = normalize(L + V);
vSpec = pow(max(dot(N, H), 0.0), 500.0);

// Unclamped diffuse — fragment uses the sign to drive a sharp terminator and
// a warm refraction band. Same direction as the basemap shadow overlay.
vLambert = dot(radial, globeLight.dir);
        `,
        "fs:#decl": /* glsl */ `
in float vSpec;
in float vLambert;
        `,
        "fs:DECKGL_FILTER_COLOR": /* glsl */ `
float lit = max(vLambert, 0.0);
// Sharper than a plain Lambert ramp: cells go dark quickly past the terminator.
float litStep = smoothstep(0.0, 0.28, lit);
float lighting = 0.22 + 0.85 * litStep;
// Subtle warm refraction band, peaks just on the lit side of the terminator.
float rim = exp(-pow((vLambert - 0.03) * 20.0, 2.0));
vec3 rimGlow = vec3(1.0, 0.55, 0.32) * rim * 0.1;
color.rgb = clamp(color.rgb * lighting + rimGlow + vec3((lit + 0.25) * vSpec * 1.6), 0.0, 1.0);
        `,
      },
    };
  }

  draw(params: any) {
    const dir = (this.props as any).lightDir;
    // SolidPolygonLayer keeps multiple models (top / side / wireframe). Push
    // the uniform to all of them.
    const models: any[] = (this.state as any).models ?? [];
    for (const m of models) {
      m?.shaderInputs?.setProps({ globeLight: { dir } });
    }
    super.draw(params);
  }
}

interface DeckGLOverlayProps {
  layers: any[];
  interleaved?: boolean;
}

type Row = {
  id: bigint;
  // Natural Earth's mapcolor7 value (1..7), 0 if missing.
  color: number;
};

const App: React.FC = () => {
  const [rows, setRows] = useState<Row[] | null>(null);
  const [lightDir, setLightDir] =
    useState<[number, number, number]>(DEFAULT_LIGHT_DIR);
  const mapRef = useRef<any>(null);

  // Orbit the light around the Z axis (one full lap every 30s), holding the
  // existing elevation so the lit hemisphere keeps the same "tilt".
  // MapLibre doesn't repaint on its own when the map is idle, so we force a
  // repaint every frame to push the new uniform into deck.gl.
  useEffect(() => {
    const ELEV = DEFAULT_LIGHT_DIR[2];
    const XY = Math.sqrt(1 - ELEV * ELEV);
    const PERIOD = 120_000;
    const start = performance.now();
    let frame = 0;
    const tick = () => {
      const t = performance.now() - start;
      const angle = ((t % PERIOD) / PERIOD) * Math.PI * 2;
      setLightDir([XY * Math.cos(angle), -XY * Math.sin(angle), ELEV]);
      frame = requestAnimationFrame(tick);
    };
    frame = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(frame);
  }, []);

  useEffect(() => {
    (async () => {
      try {
        const response = await fetch(COMPACTED_DATA);
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        const arrayBuffer = await response.arrayBuffer();
        const parsed: any[] = await new Promise((onComplete) => {
          parquetRead({ file: arrayBuffer, onComplete });
        });
        // Each row is [cell_id, color].
        const typed: Row[] = parsed.map((row) => ({
          id: BigInt.asUintN(64, row[0]),
          color: row[1],
        }));
        setRows(typed);
      } catch (e) {
        console.error(e);
      }
    })();
  }, []);

  const cells = useMemo((): CellPoly[] => {
    if (!rows) return [];
    // Group cells by palette index so we can uncompact each group together.
    // Countries that share an index are never adjacent (Natural Earth's
    // mapcolor7 is a valid 7-coloring of the world), so they're free to share
    // a colour.
    const byColor = new Map<number, bigint[]>();
    for (const r of rows) {
      let list = byColor.get(r.color);
      if (!list) {
        list = [];
        byColor.set(r.color, list);
      }
      list.push(r.id);
    }
    const result: CellPoly[] = [];
    for (const [idx, ids] of byColor) {
      const base =
        idx >= 1 && idx <= PALETTE.length ? PALETTE[idx - 1] : FALLBACK_COLOR;
      const expanded = uncompact(BigUint64Array.from(ids), RESOLUTION);
      for (const id of expanded) {
        result.push({
          boundary: cellBoundary(id),
          color: jitterByCell(base, id),
          normal: perturbForCell(id),
        });
      }
    }
    return result;
  }, [rows]);

  const layers = useMemo(
    () => [
      new GlobeShadowLayer({
        id: "globe-shadow",
        data: GLOBE_PATCHES,
        getPolygon: (d) => d.polygon,
        getFillColor: [0, 0, 0, 255],
        filled: true,
        pickable: false,
        beforeId: "watername_ocean",
        parameters: { cullMode: "back", depthCompare: "always" },
        lightDir,
      } as any),
      new TwinklePolygonLayer({
        id: "country-polygons",
        data: cells,
        getPolygon: (d) => d.boundary,
        getFillColor: (d) => d.color,
        getNormal: (d) => d.normal,
        filled: true,
        pickable: false,
        beforeId: "watername_ocean",
        parameters: { cullMode: "back", depthCompare: "always" },
        lightDir,
      } as any),
    ],
    [cells, lightDir],
  );

  return (
    <div
      style={{
        position: "absolute",
        height: "100%",
        width: "100%",
        top: 0,
        left: 0,
        background: "linear-gradient(0, #000, #223)",
      }}
    >
      <Maplibre
        id="map"
        initialViewState={INITIAL_VIEW_STATE}
        mapStyle="https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json"
        projection="globe"
        dragRotate={false}
        maxPitch={0}
      >
        <DeckGLOverlay layers={layers} interleaved />
      </Maplibre>

    </div>
  );
};

export default App;

export async function renderToDOM(container: HTMLDivElement) {
  const root = createRoot(container);
  root.render(<App />);
}

function DeckGLOverlay(props: DeckGLOverlayProps) {
  const overlay = useControl(() => new DeckOverlay(props));
  overlay.setProps(props);
  return null;
}
