name: test

# On every pull request, but only on push to master
on:
  push:
    branches:
    - master
  pull_request:

permissions:
  contents: read

jobs:
  test-node:
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      contents: read

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: volta-cli/action@615a78f6c83e116339c53b94f3f82b4d6c0b7d18 # v5.0.0

      - name: Install dependencies
        run: yarn

      - name: Check formatting
        run: yarn format:check

      - name: Check for circular dependencies and print porting order
        run: |
          python3 analyze_imports.py modules

      - name: Build packages
        run: yarn build

      - name: Run tests
        run: |
          yarn test
