name: website
on:
  push:
    branches:
      - 'main'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: |
          yarn set version 4.7.0
          yarn config set enableGlobalCache false
          yarn install --immutable
          yarn build

      - name: Build website
        run: |
          cd website
          yarn install --immutable
          yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: website/build
          clean: true
